/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TimedCommitStatusEnvironmentsStatusApplyConfiguration represents a declarative configuration of the TimedCommitStatusEnvironmentsStatus type for use
// with apply.
//
// TimedCommitStatusEnvironmentsStatus defines the observed timing status for a specific environment.
type TimedCommitStatusEnvironmentsStatusApplyConfiguration struct {
	// Branch is the name of the branch/environment.
	Branch *string `json:"branch,omitempty"`
	// Sha is the commit SHA being tracked for this environment.
	Sha *string `json:"sha,omitempty"`
	// CommitTime is when the commit was deployed to the active environment.
	CommitTime *v1.Time `json:"commitTime,omitempty"`
	// RequiredDuration is the duration that must elapse before promotion is allowed.
	// If this is updated in the spec with a pending time. The new duration will be calculated from the original CommitTime.
	// Allowing you to extend the duration of an already deployed commit, if the time has not yet elapsed.
	RequiredDuration *v1.Duration `json:"requiredDuration,omitempty"`
	// Phase represents the current phase of the timed gate.
	Phase *string `json:"phase,omitempty"`
	// AtMostDurationRemaining is the maximum amount of time remaining until the gate is satisfied.
	// This is calculated at reconciliation time. When the gate is satisfied (phase=success), this will be 0.
	AtMostDurationRemaining *v1.Duration `json:"atMostDurationRemaining,omitempty"`
}

// TimedCommitStatusEnvironmentsStatusApplyConfiguration constructs a declarative configuration of the TimedCommitStatusEnvironmentsStatus type for use with
// apply.
func TimedCommitStatusEnvironmentsStatus() *TimedCommitStatusEnvironmentsStatusApplyConfiguration {
	return &TimedCommitStatusEnvironmentsStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *TimedCommitStatusEnvironmentsStatusApplyConfiguration) WithBranch(value string) *TimedCommitStatusEnvironmentsStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithSha sets the Sha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sha field is set to the value of the last call.
func (b *TimedCommitStatusEnvironmentsStatusApplyConfiguration) WithSha(value string) *TimedCommitStatusEnvironmentsStatusApplyConfiguration {
	b.Sha = &value
	return b
}

// WithCommitTime sets the CommitTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitTime field is set to the value of the last call.
func (b *TimedCommitStatusEnvironmentsStatusApplyConfiguration) WithCommitTime(value v1.Time) *TimedCommitStatusEnvironmentsStatusApplyConfiguration {
	b.CommitTime = &value
	return b
}

// WithRequiredDuration sets the RequiredDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredDuration field is set to the value of the last call.
func (b *TimedCommitStatusEnvironmentsStatusApplyConfiguration) WithRequiredDuration(value v1.Duration) *TimedCommitStatusEnvironmentsStatusApplyConfiguration {
	b.RequiredDuration = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *TimedCommitStatusEnvironmentsStatusApplyConfiguration) WithPhase(value string) *TimedCommitStatusEnvironmentsStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithAtMostDurationRemaining sets the AtMostDurationRemaining field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AtMostDurationRemaining field is set to the value of the last call.
func (b *TimedCommitStatusEnvironmentsStatusApplyConfiguration) WithAtMostDurationRemaining(value v1.Duration) *TimedCommitStatusEnvironmentsStatusApplyConfiguration {
	b.AtMostDurationRemaining = &value
	return b
}
