rules:
  anonymous-definition:
    disable: true
  archived-uses:
    disable: true
  artipacked:
    disable: true
  bot-conditions:
    disable: true
  cache-poisoning:
    disable: true
  concurrency-limits:
    disable: true
  dangerous-triggers:
    disable: true
  dependabot-cooldown:
    disable: true
  dependabot-execution:
    disable: true
  forbidden-uses:
    disable: true
  github-env:
    disable: true
  hardcoded-container-credentials:
    disable: true
  impostor-commit:
    disable: true
  insecure-commands:
    disable: true
  known-vulnerable-actions:
    disable: true
  misfeature:
    disable: true
  obfuscation:
    disable: true
  overprovisioned-secrets:
    disable: true
  ref-confusion:
    disable: true
  ref-version-mismatch:
    disable: true
  secrets-inherit:
    disable: true
  secrets-outside-env:
    disable: true
  self-hosted-runner:
    disable: true
  stale-action-refs:
    disable: true
  superfluous-actions:
    disable: true
  template-injection:
    disable: true
  undocumented-permissions:
    disable: true
  unpinned-images:
    disable: true
  unredacted-secrets:
    disable: true
  unsound-condition:
    disable: true
  unsound-contains:
    disable: true
  use-trusted-publishing:
    disable: true
