coverage:
  status:
    # allow test coverage to drop by 0.1%, assume that it's typically due to CI problems
    patch:
      default:
        threshold: 0.1
    project:
      default:
        threshold: 0.1
ignore:
  - 'api/v1alpha1'
  - 'applyconfiguration'
  - 'test'
  - 'cmd'
  - 'config'
  - 'dist'
  - 'hack'
  - 'internal/scms/mock'
  - '**/zz_generated.*'
