version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - govet
    - lll
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nakedret
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - promlinter
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    copyloopvar:
      check-alias: true
    gocritic:
      disabled-checks:
        - assignOp
        - ifElseChain
    govet:
      enable:
        - fieldalignment
  exclusions:
    rules:
      - linters:
          - lll
        path: api/.*
      - linters:
          - lll
        path: internal/.*
      - linters:
          - dupl
        path: .*_test.go
      # Disable govet for API types, because fieldalignment will fail. Maybe we can clean that up in the future.
      - linters:
          - govet
        path: api/.*
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
