issues:
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  enable:
    - errcheck
    - errorlint
    - gocritic
    - gofumpt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - testifylint
    - thelper
    - unparam
    - unused
    - usestdlibvars
    - whitespace
linters-settings:
  gocritic:
    disabled-checks:
      - assignOp  # Keep it disabled for readability
      - ifElseChain
  testifylint:
    enable-all: true
run:
  timeout: 5m
