version: "2"
run:
  allow-parallel-runners: true
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
#    - cyclop # These are difficult to refactor, do it later.
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
#    - funlen # These are difficult to refactor, do it later.
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
#    - gocognit # These are difficult to refactor, do it later.
    - goconst
    - gocritic
    - gocyclo
#    - godot # disabled for now because there are a lot of these. Enable later.
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
#    - revive # Disabled for now because there are a lot of these. Enable later.
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
    - zerologlint
  settings:
    copyloopvar:
      check-alias: true
    cyclop:
      max-complexity: 15
    gocritic:
      disabled-checks:
        - assignOp
        - ifElseChain
    gosec:
      excludes:
        - G204 # We intentionally launch subprocesses with variables in a lot of places.
        - G304 # Produces a lot of false positives where we do FS operations. Should probably enable in the future.
    importas:
      alias:
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: k8serrors
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowed-packages: [ "github.com/onsi/ginkgo/v2", "github.com/onsi/gomega" ]
  exclusions:
    rules:
      - linters:
          - lll
        path: api/.*
      - linters:
          - lll
        path: internal/.*
      - linters:
          - dupl
          - forbidigo
          - funlen
          - gosec
          - nonamedreturns
        path: .*_test.go
      - linters:
          - gosec
        path: test/*
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    paths:
      - third_party$
      - builtin$
      - examples$
