template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/argoproj-labs/gitops-promoter/internal/scms:
    config:
      dir: internal/scms/mock
      pkgname: mock
      filename: mocks.go
    interfaces:
      CommitStatusProvider:
      GitOperationsProvider:
      PullRequestProvider:
