with-expecter: true
packages:
  github.com/argoproj-labs/gitops-promoter/internal/scms:
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      PullRequestProvider:
        # Modify package-level config for this specific interface (if applicable)
        config:
          dir: "internal/scms/mock"
          outpkg: "mock"
      CommitStatusProvider:
        # Modify package-level config for this specific interface (if applicable)
        config:
          dir: "internal/scms/mock"
          outpkg: "mock"
      GitOperationsProvider:
        # Modify package-level config for this specific interface (if applicable)
        config:
          dir: "internal/scms/mock"
          outpkg: "mock"