FROM golang:1.26.4@sha256:b4f9f8a927c6e8f24da1b653f0c7ca86fd1677fe371b03f69fd416166b527268

WORKDIR /

RUN apt-get update && apt-get install -y tini && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /git


ENV PATH="${PATH}:/git"
USER 65532:65532

WORKDIR /app
COPY ./bin/gitops-promoter /app/gitops-promoter
COPY hack/git/promoter_askpass.sh /git/promoter_askpass.sh
COPY ui/web/static ./app/ui/web/static

ENTRYPOINT ["/usr/bin/tini", "-s", "--", "/app/gitops-promoter"]
