FROM golang:1.26.5@sha256:63f132d58c1f589f0dcda584933a9bb44bfda1150f1506377f5a902f34d86033

WORKDIR /

RUN apt-get update && apt-get install -y tini && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /git


ENV PATH="${PATH}:/git"
USER 65532:65532

WORKDIR /app
COPY ./bin/gitops-promoter /app/gitops-promoter
COPY hack/git/promoter_askpass.sh /git/promoter_askpass.sh
COPY ui/web/static ./app/ui/web/static

ENTRYPOINT ["/usr/bin/tini", "-s", "--", "/app/gitops-promoter"]
