# Optional: Build workflow that runs on PR. The approval check with Approve
# button is added by the GitHub App (see docs/examples/approval-check-app/).
# Copy to your repo as .github/workflows/build.yml (or keep your existing build).
#
# On the PR you get:
# - This workflow → "Build" check (success when job completes).
# - App → "Deployment approval" check (pending until Approve/Reject; Approve = success).

name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          echo "Building PR #${{ github.event.pull_request.number }}..."
          echo "Build complete."
