apiVersion: promoter.argoproj.io/v1alpha1
kind: ChangeTransferPolicy
metadata:
  name: environment
spec:
  gitRepositoryRef:
    name: example-git-repository
  proposedBranch: env/dev-next
  activeBranch: env/dev
  activeCommitStatuses:
  - key: argocd-app-health
  proposedCommitStatuses:
  - key: security-scan
  - key: promoter-previous-environment
