apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: example-promotion-strategy
spec:
  gitRepositoryRef:
    name: example-git-repo
  activeCommitStatuses:
    - key: argocd-app-health
  proposedCommitStatuses:
    - key: security-scan
  environments:
    - branch: environment/dev
    - branch: environment/test
    - branch: environment/prod
      autoMerge: false
      activeCommitStatuses:
      - key: performance-test
      proposedCommitStatuses:
      - key: deployment-freeze
status:
  conditions:
    # The Ready condition indicates that the resource has been successfully reconciled, when there is an error during
    # reconciliation, the condition will be False with a reason of ReconciliationError. When we successfully reconcile the resource,
    # the condition will be True with a reason of ReconciliationSuccess. The Ready condition is essentially a way to show reconciliation
    # errors to the user. This condition exists on all resources that have reconciliation logic.
    - type: Ready
  environments:
  - branch: environment/dev
    commitStatuses:
      - key:
        phase:
        url:
    dry:
      author:
      body:
      commitTime:
      repoURL:
      sha:
      subject:
    hydrated:
      author:
      body:
      commitTime:
      sha:
      subject:
    proposed:
      # same fields as active
    lastHealthyDryShas:
    - sha:
      time:
  - branch: environment/test
    # same fields as dev
  - branch: environment/prod
    # same fields as dev