apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  name: demo-github
spec:
  proposedCommitStatuses:
  # The DAGCommitStatus CR will maintain this ordering gate.
  - key: promoter-dag
  activeCommitStatuses:
  # The ArgoCDCommitStatus CR will maintain this commit status based on the application health.
  - key: argocd-health
  environments:
    - autoMerge: true
      branch: environment/development
    - autoMerge: true
      branch: environment/staging
    - autoMerge: false
      branch: environment/prod
  gitRepositoryRef:
    name: gitops-promoter-demo-repo
---
apiVersion: promoter.argoproj.io/v1alpha1
kind: DAGCommitStatus
metadata:
  name: demo-github
spec:
  key: promoter-dag
  promotionStrategyRef:
    name: demo-github
