# permissions for end users to edit argocdcommitstatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: argocdcommitstatus-editor-role
rules:
- apiGroups:
  - promoter.argoproj.io
  resources:
  - argocdcommitstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - promoter.argoproj.io
  resources:
  - argocdcommitstatuses/status
  verbs:
  - get
