# This rule is not used by the project promoter itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to promoter.argoproj.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: clusterscmprovider-viewer-role
rules:
- apiGroups:
  - promoter.argoproj.io
  resources:
  - clusterscmproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - promoter.argoproj.io
  resources:
  - clusterscmproviders/status
  verbs:
  - get
