---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - promoter.argoproj.io
  resources:
  - argocdcommitstatuses
  - clusterscmproviders
  - controllerconfigurations
  - gitcommitstatuses
  - gitrepositories
  - previousenvironmentcommitstatuses
  - promotionstrategies
  - revertcommits
  - scmproviders
  - timedcommitstatuses
  - webrequestcommitstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - promoter.argoproj.io
  resources:
  - argocdcommitstatuses/finalizers
  - changetransferpolicies/finalizers
  - clusterscmproviders/finalizers
  - dagcommitstatuses/finalizers
  - gitcommitstatuses/finalizers
  - gitrepositories/finalizers
  - previousenvironmentcommitstatuses/finalizers
  - promotionstrategies/finalizers
  - pullrequests/finalizers
  - scmproviders/finalizers
  - timedcommitstatuses/finalizers
  - webrequestcommitstatuses/finalizers
  verbs:
  - update
- apiGroups:
  - promoter.argoproj.io
  resources:
  - argocdcommitstatuses/status
  - changetransferpolicies/status
  - clusterscmproviders/status
  - commitstatuses/status
  - controllerconfigurations/status
  - dagcommitstatuses/status
  - gitcommitstatuses/status
  - gitrepositories/status
  - previousenvironmentcommitstatuses/status
  - promotionstrategies/status
  - pullrequests/status
  - scmproviders/status
  - timedcommitstatuses/status
  - webrequestcommitstatuses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - promoter.argoproj.io
  resources:
  - changetransferpolicies
  - pullrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - promoter.argoproj.io
  resources:
  - commitstatuses
  - dagcommitstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
