import { describe, expect, it } from 'vitest';
import { computeTopologyDepths, resolvePromotionTopologies } from '@shared/utils/dagTopology';
import type { PromotionStrategyDetails } from '@shared/types/view';

function bundleFor(
  branches: string[],
  overrides: Partial<PromotionStrategyDetails> = {},
): PromotionStrategyDetails {
  return {
    apiVersion: 'view.promoter.argoproj.io/v1alpha1',
    kind: 'PromotionStrategyDetails',
    metadata: {
      name: 'demo',
      namespace: 'default',
    },
    promotionStrategy: {
      apiVersion: 'promoter.argoproj.io/v1alpha1',
      kind: 'PromotionStrategy',
      metadata: {
        name: 'demo',
        namespace: 'default',
      },
      spec: {
        environments: branches.map((branch) => ({ branch })),
        gitRepositoryRef: { name: 'demo' },
      },
    },
    ...overrides,
  };
}

describe('resolvePromotionTopologies', () => {
  it('uses a standalone DAGCommitStatus as a dynamic graph', () => {
    const bundle = bundleFor(['dev', 'e2e', 'perf', 'prod'], {
      dagCommitStatuses: [
        {
          metadata: { name: 'release-order' },
          spec: {
            key: 'release-order',
            promotionStrategyRef: { name: 'demo' },
            environments: [
              { branch: 'dev' },
              { branch: 'e2e', dependsOn: ['dev'] },
              { branch: 'perf', dependsOn: ['dev'] },
              { branch: 'prod', dependsOn: ['e2e', 'perf'] },
            ],
          },
        },
      ],
    });

    expect(resolvePromotionTopologies(bundle)).toEqual([
      {
        key: 'release-order',
        source: { kind: 'DAGCommitStatus', name: 'release-order' },
        nodes: [
          { branch: 'dev', dependsOn: [] },
          { branch: 'e2e', dependsOn: ['dev'] },
          { branch: 'perf', dependsOn: ['dev'] },
          { branch: 'prod', dependsOn: ['e2e', 'perf'] },
        ],
        isChain: false,
        materialized: true,
      },
    ]);
  });

  it('recognizes a DAGCommitStatus generated by PreviousEnvironmentCommitStatus', () => {
    const bundle = bundleFor(['dev', 'staging', 'prod'], {
      previousEnvironmentCommitStatuses: [
        {
          metadata: { name: 'linear-order' },
          spec: {
            key: 'previous-environment',
            promotionStrategyRef: { name: 'demo' },
          },
        },
      ],
      dagCommitStatuses: [
        {
          metadata: {
            name: 'linear-order',
            ownerReferences: [
              {
                apiVersion: 'promoter.argoproj.io/v1alpha1',
                kind: 'PreviousEnvironmentCommitStatus',
                name: 'linear-order',
                uid: 'test-uid',
                controller: true,
              },
            ],
          },
          spec: {
            key: 'previous-environment',
            promotionStrategyRef: { name: 'demo' },
            environments: [
              { branch: 'dev' },
              { branch: 'staging', dependsOn: ['dev'] },
              { branch: 'prod', dependsOn: ['staging'] },
            ],
          },
        },
      ],
    });

    expect(resolvePromotionTopologies(bundle)).toEqual([
      expect.objectContaining({
        key: 'previous-environment',
        source: {
          kind: 'PreviousEnvironmentCommitStatus',
          name: 'linear-order',
        },
        isChain: true,
        materialized: true,
      }),
    ]);
  });

  it('synthesizes a temporary chain while the PECS-owned DAG is being created', () => {
    const bundle = bundleFor(['dev', 'staging', 'prod'], {
      previousEnvironmentCommitStatuses: [
        {
          metadata: { name: 'linear-order' },
          spec: {
            key: 'previous-environment',
            promotionStrategyRef: { name: 'demo' },
          },
        },
      ],
    });

    expect(resolvePromotionTopologies(bundle)).toEqual([
      {
        key: 'previous-environment',
        source: {
          kind: 'PreviousEnvironmentCommitStatus',
          name: 'linear-order',
        },
        nodes: [
          { branch: 'dev', dependsOn: [] },
          { branch: 'staging', dependsOn: ['dev'] },
          { branch: 'prod', dependsOn: ['staging'] },
        ],
        isChain: true,
        materialized: false,
      },
    ]);
  });
});

describe('computeTopologyDepths', () => {
  it('places fan-out and fan-in branches into stable graph rows', () => {
    expect(
      computeTopologyDepths([
        { branch: 'dev', dependsOn: [] },
        { branch: 'e2e', dependsOn: ['dev'] },
        { branch: 'perf', dependsOn: ['dev'] },
        { branch: 'prod', dependsOn: ['e2e', 'perf'] },
      ]),
    ).toEqual(
      new Map([
        ['dev', 0],
        ['e2e', 1],
        ['perf', 1],
        ['prod', 2],
      ]),
    );
  });
});
