#!/usr/bin/env bash
# Generates ui/extension/iconStyles.generated.ts from the logo SVGs.
# Run from repo root: hack/extension-icon-styles.sh (or make generate-extension-icon-styles)
#
# Produces CSS for the Argo CD app view tab icon with 4 states:
# - Default: primary icon, single color #8fa4b1 (matches Argo CD unselected)
# - Selected: primary icon, single color #495763 (matches Argo CD selected)
# - Hover (light): full-color primary icon
# - Hover (dark): full-color secondary icon (for .theme-dark)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
PRIMARY_SVG="$REPO_ROOT/docs/assets/logo/icon/primary.svg"
SECONDARY_SVG="$REPO_ROOT/docs/assets/logo/icon/secondary.svg"
OUT_FILE="$REPO_ROOT/ui/extension/iconStyles.generated.ts"

COLOR_DEFAULT="#8fa4b1"
COLOR_SELECTED="#495763"

minify_svg() {
  sed 's/>[[:space:]]*</></g' | tr -d '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

replace_svg_fills() {
  local color="$1"
  sed -E "s/fill:[[:space:]]*#[0-9a-fA-F]{3,8}/fill: $color/g"
}

svg_to_data_uri() {
  local minified
  minified=$(minify_svg)
  echo -n "data:image/svg+xml;base64,"
  echo -n "$minified" | base64 | tr -d '\n'
}

primary_svg=$(<"$PRIMARY_SVG")
secondary_svg=$(<"$SECONDARY_SVG")

default_svg=$(echo "$primary_svg" | replace_svg_fills "$COLOR_DEFAULT")
selected_svg=$(echo "$primary_svg" | replace_svg_fills "$COLOR_SELECTED")

default_data_uri=$(echo "$default_svg" | svg_to_data_uri)
selected_data_uri=$(echo "$selected_svg" | svg_to_data_uri)
hover_light_data_uri=$(echo "$primary_svg" | svg_to_data_uri)
hover_dark_data_uri=$(echo "$secondary_svg" | svg_to_data_uri)

selector='.fa.gitops-promoter-app-view-icon,
.gitops-promoter-app-view-icon'
selector_before='.fa.gitops-promoter-app-view-icon::before,
.gitops-promoter-app-view-icon::before'
selector_selected='.fa.gitops-promoter-app-view-icon.selected,
.gitops-promoter-app-view-icon.selected'
selector_hover='.fa.gitops-promoter-app-view-icon:hover,
.gitops-promoter-app-view-icon:hover'
selector_hover_dark='.theme-dark .fa.gitops-promoter-app-view-icon:hover,
.theme-dark .gitops-promoter-app-view-icon:hover'
selector_selected_hover='.fa.gitops-promoter-app-view-icon.selected:hover,
.gitops-promoter-app-view-icon.selected:hover'
selector_selected_hover_dark='.theme-dark .fa.gitops-promoter-app-view-icon.selected:hover,
.theme-dark .gitops-promoter-app-view-icon.selected:hover'

css="${selector} {
  font-size: 0 !important;
  display: inline-block;
  vertical-align: -3px;
  width: 1.5rem;
  height: 1.5rem;
  margin-left: 0.5rem;
  margin-right: 0.5rem;
  background: url(\"${default_data_uri}\") no-repeat center;
  background-size: contain;
}
${selector_before} {
  content: none !important;
}
${selector_selected} {
  background-image: url(\"${selected_data_uri}\");
}
${selector_hover} {
  background-image: url(\"${hover_light_data_uri}\");
}
${selector_hover_dark} {
  background-image: url(\"${hover_dark_data_uri}\");
}
${selector_selected_hover} {
  background-image: url(\"${selected_data_uri}\");
}
${selector_selected_hover_dark} {
  background-image: url(\"${selected_data_uri}\");
}
"

# Escape backticks and $ for TypeScript template literal
escaped_css="${css//\`/\\\`}"
escaped_css="${escaped_css//\$/\\\$}"

{
  echo '// Code generated by hack/extension-icon-styles.sh. DO NOT EDIT.'
  echo ''
  echo -n 'export const ICON_STYLES = `'
  printf '%s' "$escaped_css"
  echo '`;'
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
