/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ApplicationsSelectedApplyConfiguration represents a declarative configuration of the ApplicationsSelected type for use
// with apply.
//
// ApplicationsSelected represents the Argo CD applications that are selected by the commit status.
type ApplicationsSelectedApplyConfiguration struct {
	// Namespace is the namespace of the Argo CD application.
	Namespace *string `json:"namespace,omitempty"`
	// Name is the name of the Argo CD application.
	Name *string `json:"name,omitempty"`
	// Phase is the current phase of the commit status.
	Phase *apiv1alpha1.CommitStatusPhase `json:"phase,omitempty"`
	// Sha is the commit SHA that this status is associated with.
	Sha *string `json:"sha,omitempty"`
	// LastTransitionTime is the last time the phase transitioned.
	LastTransitionTime *v1.Time `json:"lastTransitionTime,omitempty"`
	// Environment is the syncSource.targetBranch of the Argo CD application (in effect, its environment).
	Environment *string `json:"environment,omitempty"`
	// ClusterName is the name of the cluster that the application manifest is deployed to. An empty string indicates
	// the local cluster.
	ClusterName *string `json:"clusterName,omitempty"`
}

// ApplicationsSelectedApplyConfiguration constructs a declarative configuration of the ApplicationsSelected type for use with
// apply.
func ApplicationsSelected() *ApplicationsSelectedApplyConfiguration {
	return &ApplicationsSelectedApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ApplicationsSelectedApplyConfiguration) WithNamespace(value string) *ApplicationsSelectedApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ApplicationsSelectedApplyConfiguration) WithName(value string) *ApplicationsSelectedApplyConfiguration {
	b.Name = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ApplicationsSelectedApplyConfiguration) WithPhase(value apiv1alpha1.CommitStatusPhase) *ApplicationsSelectedApplyConfiguration {
	b.Phase = &value
	return b
}

// WithSha sets the Sha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sha field is set to the value of the last call.
func (b *ApplicationsSelectedApplyConfiguration) WithSha(value string) *ApplicationsSelectedApplyConfiguration {
	b.Sha = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *ApplicationsSelectedApplyConfiguration) WithLastTransitionTime(value v1.Time) *ApplicationsSelectedApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}

// WithEnvironment sets the Environment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Environment field is set to the value of the last call.
func (b *ApplicationsSelectedApplyConfiguration) WithEnvironment(value string) *ApplicationsSelectedApplyConfiguration {
	b.Environment = &value
	return b
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *ApplicationsSelectedApplyConfiguration) WithClusterName(value string) *ApplicationsSelectedApplyConfiguration {
	b.ClusterName = &value
	return b
}
