/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ArgoCDCommitStatusStatusApplyConfiguration represents a declarative configuration of the ArgoCDCommitStatusStatus type for use
// with apply.
//
// ArgoCDCommitStatusStatus defines the observed state of ArgoCDCommitStatus.
type ArgoCDCommitStatusStatusApplyConfiguration struct {
	// ApplicationsSelected represents the Argo CD applications that are selected by the commit status.
	// This field is sorted by environment (same order as the referenced PromotionStrategy), then namespace, then name.
	ApplicationsSelected []ApplicationsSelectedApplyConfiguration `json:"applicationsSelected,omitempty"`
	// Conditions Represents the observations of the current state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ArgoCDCommitStatusStatusApplyConfiguration constructs a declarative configuration of the ArgoCDCommitStatusStatus type for use with
// apply.
func ArgoCDCommitStatusStatus() *ArgoCDCommitStatusStatusApplyConfiguration {
	return &ArgoCDCommitStatusStatusApplyConfiguration{}
}

// WithApplicationsSelected adds the given value to the ApplicationsSelected field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ApplicationsSelected field.
func (b *ArgoCDCommitStatusStatusApplyConfiguration) WithApplicationsSelected(values ...*ApplicationsSelectedApplyConfiguration) *ArgoCDCommitStatusStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithApplicationsSelected")
		}
		b.ApplicationsSelected = append(b.ApplicationsSelected, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ArgoCDCommitStatusStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ArgoCDCommitStatusStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
