/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// AzureDevOpsApplyConfiguration represents a declarative configuration of the AzureDevOps type for use
// with apply.
//
// AzureDevOps is an Azure DevOps SCM provider configuration. It is used to configure the Azure DevOps settings.
type AzureDevOpsApplyConfiguration struct {
	// Organization is the Azure DevOps organization name.
	Organization *string `json:"organization,omitempty"`
	// Domain is the Azure DevOps domain, such as "dev.azure.com". If using the default Azure DevOps domain, leave this field empty.
	Domain *string `json:"domain,omitempty"`
}

// AzureDevOpsApplyConfiguration constructs a declarative configuration of the AzureDevOps type for use with
// apply.
func AzureDevOps() *AzureDevOpsApplyConfiguration {
	return &AzureDevOpsApplyConfiguration{}
}

// WithOrganization sets the Organization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Organization field is set to the value of the last call.
func (b *AzureDevOpsApplyConfiguration) WithOrganization(value string) *AzureDevOpsApplyConfiguration {
	b.Organization = &value
	return b
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *AzureDevOpsApplyConfiguration) WithDomain(value string) *AzureDevOpsApplyConfiguration {
	b.Domain = &value
	return b
}
