/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// BearerAuthApplyConfiguration represents a declarative configuration of the BearerAuth type for use
// with apply.
//
// BearerAuth defines Bearer token authentication.
//
// Bearer tokens are commonly used for API authentication. The token is sent
// in the Authorization header: "Authorization: Bearer <token>"
//
// Common use cases:
// - API keys
// - JWT tokens
// - Personal access tokens
// - Static authentication tokens
//
// The token must be stored in a Kubernetes secret and referenced via secretRef:
//
// bearer:
// secretRef:
// name: my-bearer-token-secret  # secret must contain key "token"
type BearerAuthApplyConfiguration struct {
	// SecretRef references a secret containing the bearer token.
	// The secret must contain key "token".
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// BearerAuthApplyConfiguration constructs a declarative configuration of the BearerAuth type for use with
// apply.
func BearerAuth() *BearerAuthApplyConfiguration {
	return &BearerAuthApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *BearerAuthApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *BearerAuthApplyConfiguration {
	b.SecretRef = &value
	return b
}
