/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// BitbucketDataCenterApplyConfiguration represents a declarative configuration of the BitbucketDataCenter type for use
// with apply.
//
// BitbucketDataCenter is a Bitbucket DataCenter/Server SCM provider configuration.
type BitbucketDataCenterApplyConfiguration struct {
	// Domain is the Bitbucket DataCenter/Server domain, such as "bitbucket.mycompany.com".
	Domain *string `json:"domain,omitempty"`
}

// BitbucketDataCenterApplyConfiguration constructs a declarative configuration of the BitbucketDataCenter type for use with
// apply.
func BitbucketDataCenter() *BitbucketDataCenterApplyConfiguration {
	return &BitbucketDataCenterApplyConfiguration{}
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *BitbucketDataCenterApplyConfiguration) WithDomain(value string) *BitbucketDataCenterApplyConfiguration {
	b.Domain = &value
	return b
}
