/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// ChangeTransferPolicySpecApplyConfiguration represents a declarative configuration of the ChangeTransferPolicySpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// ChangeTransferPolicySpec defines the desired state of ChangeTransferPolicy
type ChangeTransferPolicySpecApplyConfiguration struct {
	// RepositoryReference what repository to open the PR on.
	RepositoryReference *ObjectReferenceApplyConfiguration `json:"gitRepositoryRef,omitempty"`
	// ProposedBranch staging hydrated branch
	// Must not start with '-', contain ':', or contain '..'.
	ProposedBranch *string `json:"proposedBranch,omitempty"`
	// ActiveBranch staging hydrated branch
	// Must not start with '-', contain ':', or contain '..'.
	ActiveBranch *string `json:"activeBranch,omitempty"`
	// ActivePath is an optional repository subpath for this policy's active state.
	// When set, hydrator metadata is read from <activePath>/hydrator.metadata.
	ActivePath *string `json:"activePath,omitempty"`
	AutoMerge  *bool   `json:"autoMerge,omitempty"`
	// ActiveCommitStatuses lists the statuses to be monitored on the active branch
	ActiveCommitStatuses []CommitStatusSelectorApplyConfiguration `json:"activeCommitStatuses,omitempty"`
	// ProposedCommitStatuses lists the statuses to be monitored on the proposed branch
	ProposedCommitStatuses []CommitStatusSelectorApplyConfiguration `json:"proposedCommitStatuses,omitempty"`
	// MergeComments lists comments to post on the PR when all merge conditions are met,
	// instead of merging the PR directly via the SCM API. An external system (e.g. Prow)
	// is expected to perform the actual merge after seeing these comments.
	// Requires autoMerge: true. Labels and comments may be combined.
	MergeComments []string `json:"mergeComments,omitempty"`
	// MergeLabels lists labels to add to the PR when all merge conditions are met,
	// instead of merging the PR directly via the SCM API. An external system (e.g. Tide)
	// is expected to perform the actual merge after seeing these labels.
	// Requires autoMerge: true. Labels and comments may be combined.
	MergeLabels []string `json:"mergeLabels,omitempty"`
}

// ChangeTransferPolicySpecApplyConfiguration constructs a declarative configuration of the ChangeTransferPolicySpec type for use with
// apply.
func ChangeTransferPolicySpec() *ChangeTransferPolicySpecApplyConfiguration {
	return &ChangeTransferPolicySpecApplyConfiguration{}
}

// WithRepositoryReference sets the RepositoryReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositoryReference field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithRepositoryReference(value *ObjectReferenceApplyConfiguration) *ChangeTransferPolicySpecApplyConfiguration {
	b.RepositoryReference = value
	return b
}

// WithProposedBranch sets the ProposedBranch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProposedBranch field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithProposedBranch(value string) *ChangeTransferPolicySpecApplyConfiguration {
	b.ProposedBranch = &value
	return b
}

// WithActiveBranch sets the ActiveBranch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveBranch field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithActiveBranch(value string) *ChangeTransferPolicySpecApplyConfiguration {
	b.ActiveBranch = &value
	return b
}

// WithActivePath sets the ActivePath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActivePath field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithActivePath(value string) *ChangeTransferPolicySpecApplyConfiguration {
	b.ActivePath = &value
	return b
}

// WithAutoMerge sets the AutoMerge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoMerge field is set to the value of the last call.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithAutoMerge(value bool) *ChangeTransferPolicySpecApplyConfiguration {
	b.AutoMerge = &value
	return b
}

// WithActiveCommitStatuses adds the given value to the ActiveCommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActiveCommitStatuses field.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithActiveCommitStatuses(values ...*CommitStatusSelectorApplyConfiguration) *ChangeTransferPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithActiveCommitStatuses")
		}
		b.ActiveCommitStatuses = append(b.ActiveCommitStatuses, *values[i])
	}
	return b
}

// WithProposedCommitStatuses adds the given value to the ProposedCommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProposedCommitStatuses field.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithProposedCommitStatuses(values ...*CommitStatusSelectorApplyConfiguration) *ChangeTransferPolicySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProposedCommitStatuses")
		}
		b.ProposedCommitStatuses = append(b.ProposedCommitStatuses, *values[i])
	}
	return b
}

// WithMergeComments adds the given value to the MergeComments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MergeComments field.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithMergeComments(values ...string) *ChangeTransferPolicySpecApplyConfiguration {
	for i := range values {
		b.MergeComments = append(b.MergeComments, values[i])
	}
	return b
}

// WithMergeLabels adds the given value to the MergeLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MergeLabels field.
func (b *ChangeTransferPolicySpecApplyConfiguration) WithMergeLabels(values ...string) *ChangeTransferPolicySpecApplyConfiguration {
	for i := range values {
		b.MergeLabels = append(b.MergeLabels, values[i])
	}
	return b
}
