/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// CommitBranchStateApplyConfiguration represents a declarative configuration of the CommitBranchState type for use
// with apply.
//
// CommitBranchState defines the state of a branch in a ChangeTransferPolicy.
type CommitBranchStateApplyConfiguration struct {
	// Dry is the dry state of the branch, which is the commit that is being proposed.
	Dry *CommitShaStateApplyConfiguration `json:"dry,omitempty"`
	// Hydrated is the hydrated state of the branch, which is the commit that is currently being worked on.
	Hydrated *CommitShaStateApplyConfiguration `json:"hydrated,omitempty"`
	// Note is the hydrator metadata from the git note attached to the hydrated commit.
	Note *HydratorMetadataApplyConfiguration `json:"note,omitempty"`
	// CommitStatuses is a list of commit statuses that are being monitored for this branch.
	CommitStatuses []ChangeRequestPolicyCommitStatusPhaseApplyConfiguration `json:"commitStatuses,omitempty"`
}

// CommitBranchStateApplyConfiguration constructs a declarative configuration of the CommitBranchState type for use with
// apply.
func CommitBranchState() *CommitBranchStateApplyConfiguration {
	return &CommitBranchStateApplyConfiguration{}
}

// WithDry sets the Dry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Dry field is set to the value of the last call.
func (b *CommitBranchStateApplyConfiguration) WithDry(value *CommitShaStateApplyConfiguration) *CommitBranchStateApplyConfiguration {
	b.Dry = value
	return b
}

// WithHydrated sets the Hydrated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hydrated field is set to the value of the last call.
func (b *CommitBranchStateApplyConfiguration) WithHydrated(value *CommitShaStateApplyConfiguration) *CommitBranchStateApplyConfiguration {
	b.Hydrated = value
	return b
}

// WithNote sets the Note field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Note field is set to the value of the last call.
func (b *CommitBranchStateApplyConfiguration) WithNote(value *HydratorMetadataApplyConfiguration) *CommitBranchStateApplyConfiguration {
	b.Note = value
	return b
}

// WithCommitStatuses adds the given value to the CommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CommitStatuses field.
func (b *CommitBranchStateApplyConfiguration) WithCommitStatuses(values ...*ChangeRequestPolicyCommitStatusPhaseApplyConfiguration) *CommitBranchStateApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCommitStatuses")
		}
		b.CommitStatuses = append(b.CommitStatuses, *values[i])
	}
	return b
}
