/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// ControllerConfigurationSpecApplyConfiguration represents a declarative configuration of the ControllerConfigurationSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// ControllerConfigurationSpec defines the desired state of ControllerConfiguration.
//
// This spec contains the global configuration for all controllers in the promoter system.
// Each controller has its own configuration section that specifies WorkQueue settings,
// rate limiters, and other controller-specific parameters. All fields should be required,
// with defaults set in manifests rather than in code.
type ControllerConfigurationSpecApplyConfiguration struct {
	// PromotionStrategy contains the configuration for the PromotionStrategy controller,
	// including WorkQueue settings that control reconciliation behavior.
	PromotionStrategy *PromotionStrategyConfigurationApplyConfiguration `json:"promotionStrategy,omitempty"`
	// ChangeTransferPolicy contains the configuration for the ChangeTransferPolicy controller,
	// including WorkQueue settings that control reconciliation behavior.
	ChangeTransferPolicy *ChangeTransferPolicyConfigurationApplyConfiguration `json:"changeTransferPolicy,omitempty"`
	// PullRequest contains the configuration for the PullRequest controller,
	// including WorkQueue settings and pull request template configuration.
	PullRequest *PullRequestConfigurationApplyConfiguration `json:"pullRequest,omitempty"`
	// CommitStatus contains the configuration for the CommitStatus controller,
	// including WorkQueue settings that control reconciliation behavior.
	CommitStatus *CommitStatusConfigurationApplyConfiguration `json:"commitStatus,omitempty"`
	// ArgoCDCommitStatus contains the configuration for the ArgoCDCommitStatus controller,
	// including WorkQueue settings that control reconciliation behavior.
	ArgoCDCommitStatus *ArgoCDCommitStatusConfigurationApplyConfiguration `json:"argocdCommitStatus,omitempty"`
	// TimedCommitStatus contains the configuration for the TimedCommitStatus controller,
	// including WorkQueue settings that control reconciliation behavior.
	TimedCommitStatus *TimedCommitStatusConfigurationApplyConfiguration `json:"timedCommitStatus,omitempty"`
	// GitCommitStatus contains the configuration for the GitCommitStatus controller,
	// including WorkQueue settings that control reconciliation behavior.
	GitCommitStatus *GitCommitStatusConfigurationApplyConfiguration `json:"gitCommitStatus,omitempty"`
}

// ControllerConfigurationSpecApplyConfiguration constructs a declarative configuration of the ControllerConfigurationSpec type for use with
// apply.
func ControllerConfigurationSpec() *ControllerConfigurationSpecApplyConfiguration {
	return &ControllerConfigurationSpecApplyConfiguration{}
}

// WithPromotionStrategy sets the PromotionStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategy field is set to the value of the last call.
func (b *ControllerConfigurationSpecApplyConfiguration) WithPromotionStrategy(value *PromotionStrategyConfigurationApplyConfiguration) *ControllerConfigurationSpecApplyConfiguration {
	b.PromotionStrategy = value
	return b
}

// WithChangeTransferPolicy sets the ChangeTransferPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChangeTransferPolicy field is set to the value of the last call.
func (b *ControllerConfigurationSpecApplyConfiguration) WithChangeTransferPolicy(value *ChangeTransferPolicyConfigurationApplyConfiguration) *ControllerConfigurationSpecApplyConfiguration {
	b.ChangeTransferPolicy = value
	return b
}

// WithPullRequest sets the PullRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullRequest field is set to the value of the last call.
func (b *ControllerConfigurationSpecApplyConfiguration) WithPullRequest(value *PullRequestConfigurationApplyConfiguration) *ControllerConfigurationSpecApplyConfiguration {
	b.PullRequest = value
	return b
}

// WithCommitStatus sets the CommitStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitStatus field is set to the value of the last call.
func (b *ControllerConfigurationSpecApplyConfiguration) WithCommitStatus(value *CommitStatusConfigurationApplyConfiguration) *ControllerConfigurationSpecApplyConfiguration {
	b.CommitStatus = value
	return b
}

// WithArgoCDCommitStatus sets the ArgoCDCommitStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArgoCDCommitStatus field is set to the value of the last call.
func (b *ControllerConfigurationSpecApplyConfiguration) WithArgoCDCommitStatus(value *ArgoCDCommitStatusConfigurationApplyConfiguration) *ControllerConfigurationSpecApplyConfiguration {
	b.ArgoCDCommitStatus = value
	return b
}

// WithTimedCommitStatus sets the TimedCommitStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimedCommitStatus field is set to the value of the last call.
func (b *ControllerConfigurationSpecApplyConfiguration) WithTimedCommitStatus(value *TimedCommitStatusConfigurationApplyConfiguration) *ControllerConfigurationSpecApplyConfiguration {
	b.TimedCommitStatus = value
	return b
}

// WithGitCommitStatus sets the GitCommitStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GitCommitStatus field is set to the value of the last call.
func (b *ControllerConfigurationSpecApplyConfiguration) WithGitCommitStatus(value *GitCommitStatusConfigurationApplyConfiguration) *ControllerConfigurationSpecApplyConfiguration {
	b.GitCommitStatus = value
	return b
}
