/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CronWindowApplyConfiguration represents a declarative configuration of the CronWindow type for use
// with apply.
//
// CronWindow defines a recurring time window using a cron expression and a duration.
type CronWindowApplyConfiguration struct {
	// Description is an optional human-readable explanation of this window
	// (e.g. "US East business hours", "Holiday deployment freeze").
	Description *string `json:"description,omitempty"`
	// Cron is a standard 5-field cron expression defining the start of the window
	// (minute hour day-of-month month day-of-week). For example "0 9 * * 1-5" means
	// Monday–Friday at 09:00 in the configured timezone.
	Cron *string `json:"cron,omitempty"`
	// Duration is how long the window remains open after the cron trigger.
	// The duration should be in a format accepted by Go's time.ParseDuration function, e.g., "8h", "30m", "2h30m".
	Duration *v1.Duration `json:"duration,omitempty"`
	// Timezone overrides the spec-level default timezone for this specific window.
	// If not set, the spec-level timezone (or UTC if that is also not set) is used.
	Timezone *string `json:"timezone,omitempty"`
}

// CronWindowApplyConfiguration constructs a declarative configuration of the CronWindow type for use with
// apply.
func CronWindow() *CronWindowApplyConfiguration {
	return &CronWindowApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *CronWindowApplyConfiguration) WithDescription(value string) *CronWindowApplyConfiguration {
	b.Description = &value
	return b
}

// WithCron sets the Cron field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cron field is set to the value of the last call.
func (b *CronWindowApplyConfiguration) WithCron(value string) *CronWindowApplyConfiguration {
	b.Cron = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *CronWindowApplyConfiguration) WithDuration(value v1.Duration) *CronWindowApplyConfiguration {
	b.Duration = &value
	return b
}

// WithTimezone sets the Timezone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timezone field is set to the value of the last call.
func (b *CronWindowApplyConfiguration) WithTimezone(value string) *CronWindowApplyConfiguration {
	b.Timezone = &value
	return b
}
