/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// DAGEnvironmentApplyConfiguration represents a declarative configuration of the DAGEnvironment type for use
// with apply.
//
// DAGEnvironment is a single node in the promotion dependency graph.
type DAGEnvironmentApplyConfiguration struct {
	// Branch is the name of the active branch for the environment. It must match a branch declared
	// in the referenced PromotionStrategy's environments.
	// Must not start with '-', contain ':', or contain '..'.
	Branch *string `json:"branch,omitempty"`
	// DependsOn is the list of upstream branches this environment depends on. The environment is
	// only eligible for promotion once every branch listed here is satisfied. An empty or omitted
	// list makes this environment a root of the graph.
	// Each item must not start with '-', contain ':', or contain '..'.
	DependsOn []string `json:"dependsOn,omitempty"`
}

// DAGEnvironmentApplyConfiguration constructs a declarative configuration of the DAGEnvironment type for use with
// apply.
func DAGEnvironment() *DAGEnvironmentApplyConfiguration {
	return &DAGEnvironmentApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *DAGEnvironmentApplyConfiguration) WithBranch(value string) *DAGEnvironmentApplyConfiguration {
	b.Branch = &value
	return b
}

// WithDependsOn adds the given value to the DependsOn field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DependsOn field.
func (b *DAGEnvironmentApplyConfiguration) WithDependsOn(values ...string) *DAGEnvironmentApplyConfiguration {
	for i := range values {
		b.DependsOn = append(b.DependsOn, values[i])
	}
	return b
}
