/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// DependentsSuccessfulCommitStatusStatusApplyConfiguration represents a declarative configuration of the DependentsSuccessfulCommitStatusStatus type for use
// with apply.
//
// DependentsSuccessfulCommitStatusStatus defines the observed state of DependentsSuccessfulCommitStatus.
type DependentsSuccessfulCommitStatusStatusApplyConfiguration struct {
	// ObservedGeneration is the .metadata.generation that this status was reconciled from.
	// Because status is written via Server-Side Apply with ForceOwnership (which has no
	// optimistic-concurrency check), this field is the canonical way to detect stale
	// status writes: compare status.observedGeneration with metadata.generation.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// Conditions represent the latest available observations of an object's state
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// InstanceID mirrors metadata.labels[promoter.argoproj.io/instance-id] stamped on each
	// reconcile attempt by this install's controller, including when Ready=False; omitted
	// when the resource has no instance-id label (default install).
	InstanceID *string `json:"instanceID,omitempty"`
}

// DependentsSuccessfulCommitStatusStatusApplyConfiguration constructs a declarative configuration of the DependentsSuccessfulCommitStatusStatus type for use with
// apply.
func DependentsSuccessfulCommitStatusStatus() *DependentsSuccessfulCommitStatusStatusApplyConfiguration {
	return &DependentsSuccessfulCommitStatusStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *DependentsSuccessfulCommitStatusStatusApplyConfiguration) WithObservedGeneration(value int64) *DependentsSuccessfulCommitStatusStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *DependentsSuccessfulCommitStatusStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *DependentsSuccessfulCommitStatusStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithInstanceID sets the InstanceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceID field is set to the value of the last call.
func (b *DependentsSuccessfulCommitStatusStatusApplyConfiguration) WithInstanceID(value string) *DependentsSuccessfulCommitStatusStatusApplyConfiguration {
	b.InstanceID = &value
	return b
}
