/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

// DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration represents a declarative configuration of the DependentsSuccessfulCommitStatusUpstreamStatus type for use
// with apply.
//
// DependentsSuccessfulCommitStatusUpstreamStatus reports whether a transitive upstream branch
// is satisfied for this environment's promotion target.
type DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration struct {
	// Branch is the upstream environment branch name.
	Branch *string `json:"branch,omitempty"`
	// Satisfied is true when the upstream has promoted and is healthy for this environment's target dry SHA.
	Satisfied *bool `json:"satisfied,omitempty"`
	// Reason explains why the upstream is not satisfied. Omitted when satisfied is true.
	Reason *string `json:"reason,omitempty"`
}

// DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration constructs a declarative configuration of the DependentsSuccessfulCommitStatusUpstreamStatus type for use with
// apply.
func DependentsSuccessfulCommitStatusUpstreamStatus() *DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	return &DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration) WithBranch(value string) *DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithSatisfied sets the Satisfied field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Satisfied field is set to the value of the last call.
func (b *DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration) WithSatisfied(value bool) *DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	b.Satisfied = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration) WithReason(value string) *DependentsSuccessfulCommitStatusUpstreamStatusApplyConfiguration {
	b.Reason = &value
	return b
}
