/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DryShaValidationEnvironmentStatusApplyConfiguration represents a declarative configuration of the DryShaValidationEnvironmentStatus type for use
// with apply.
//
// DryShaValidationEnvironmentStatus is the most recent gate evaluation for one environment.
type DryShaValidationEnvironmentStatusApplyConfiguration struct {
	// Branch is the environment's active branch.
	Branch *string `json:"branch,omitempty"`
	// TargetDrySha is the dry commit this environment is currently promoting, resolved from the
	// hydrator note and falling back to the proposed dry SHA. Empty when nothing is in flight.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	TargetDrySha *string `json:"targetDrySha,omitempty"`
	// Phase mirrors the phase written to this environment's generated CommitStatus.
	Phase *apiv1alpha1.CommitStatusPhase `json:"phase,omitempty"`
	// ValidatedIn is the lower environment branch whose history proved TargetDrySha was active and
	// healthy there. Empty while the gate is pending.
	ValidatedIn *string `json:"validatedIn,omitempty"`
	// ValidatedAt is the commit time of the merge commit that made TargetDrySha active in
	// ValidatedIn. Empty while the gate is pending.
	ValidatedAt *v1.Time `json:"validatedAt,omitempty"`
	// CommitsScanned is how many first-parent commits were walked in the upstream environments on
	// the last evaluation, bounded by spec.lookbackLimit. It tells "not validated yet" apart from
	// "validated, but it aged out of the lookback window".
	CommitsScanned *int32 `json:"commitsScanned,omitempty"`
	// LastEvaluationTime is when this environment was last evaluated.
	LastEvaluationTime *v1.Time `json:"lastEvaluationTime,omitempty"`
}

// DryShaValidationEnvironmentStatusApplyConfiguration constructs a declarative configuration of the DryShaValidationEnvironmentStatus type for use with
// apply.
func DryShaValidationEnvironmentStatus() *DryShaValidationEnvironmentStatusApplyConfiguration {
	return &DryShaValidationEnvironmentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *DryShaValidationEnvironmentStatusApplyConfiguration) WithBranch(value string) *DryShaValidationEnvironmentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithTargetDrySha sets the TargetDrySha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetDrySha field is set to the value of the last call.
func (b *DryShaValidationEnvironmentStatusApplyConfiguration) WithTargetDrySha(value string) *DryShaValidationEnvironmentStatusApplyConfiguration {
	b.TargetDrySha = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *DryShaValidationEnvironmentStatusApplyConfiguration) WithPhase(value apiv1alpha1.CommitStatusPhase) *DryShaValidationEnvironmentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithValidatedIn sets the ValidatedIn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValidatedIn field is set to the value of the last call.
func (b *DryShaValidationEnvironmentStatusApplyConfiguration) WithValidatedIn(value string) *DryShaValidationEnvironmentStatusApplyConfiguration {
	b.ValidatedIn = &value
	return b
}

// WithValidatedAt sets the ValidatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValidatedAt field is set to the value of the last call.
func (b *DryShaValidationEnvironmentStatusApplyConfiguration) WithValidatedAt(value v1.Time) *DryShaValidationEnvironmentStatusApplyConfiguration {
	b.ValidatedAt = &value
	return b
}

// WithCommitsScanned sets the CommitsScanned field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitsScanned field is set to the value of the last call.
func (b *DryShaValidationEnvironmentStatusApplyConfiguration) WithCommitsScanned(value int32) *DryShaValidationEnvironmentStatusApplyConfiguration {
	b.CommitsScanned = &value
	return b
}

// WithLastEvaluationTime sets the LastEvaluationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastEvaluationTime field is set to the value of the last call.
func (b *DryShaValidationEnvironmentStatusApplyConfiguration) WithLastEvaluationTime(value v1.Time) *DryShaValidationEnvironmentStatusApplyConfiguration {
	b.LastEvaluationTime = &value
	return b
}
