/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// DryShaValidationCommitStatusSpecApplyConfiguration represents a declarative configuration of the DryShaValidationCommitStatusSpec type for use
// with apply.
//
// DryShaValidationCommitStatusSpec defines the desired state of DryShaValidationCommitStatus.
type DryShaValidationCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef is a reference to the PromotionStrategy this gate applies to. The
	// controller watches it and, for each environment, reports whether the dry commit being
	// promoted has already been validated in a lower environment.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Key is the commit status key referenced in the PromotionStrategy's proposedCommitStatuses.
	// It must match a key declared there so the gate this controller produces is enforced.
	// Must be lowercase alphanumeric with hyphens, 1–63 characters (pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$).
	Key *string `json:"key,omitempty"`
	// Environments declares the promotion dependency graph. Each entry names an environment branch
	// and the lower branches it depends on; a dry commit validated in any of those (transitively)
	// satisfies this environment. An entry with no dependsOn is a graph root and always passes.
	// When omitted, a linear chain is derived from the referenced PromotionStrategy's
	// spec.environments order (each environment depends on the one before it).
	// The graph must be acyclic; cycles and references to unknown branches are rejected.
	Environments []DryShaValidationEnvironmentApplyConfiguration `json:"environments,omitempty"`
	// LookbackLimit is how many first-parent commits to scan on each upstream environment's active
	// branch when looking for the dry commit. A dry commit promoted longer ago than this many
	// promotions in every upstream reads as unvalidated, and the gate stays pending.
	LookbackLimit *int32 `json:"lookbackLimit,omitempty"`
	// URL generates the URL to use on the per-environment CommitStatus (SCM details link), for
	// example a link into the Promoter UI that highlights this environment's upstreams.
	// Optional; when empty, no URL is set on the child CommitStatus. The template receives
	// .Environment, .DryShaValidationCommitStatus, .PromotionStrategy, .DependsOn and
	// .DependsOnQuery (see controller docs).
	URL *URLConfigApplyConfiguration `json:"url,omitempty"`
}

// DryShaValidationCommitStatusSpecApplyConfiguration constructs a declarative configuration of the DryShaValidationCommitStatusSpec type for use with
// apply.
func DryShaValidationCommitStatusSpec() *DryShaValidationCommitStatusSpecApplyConfiguration {
	return &DryShaValidationCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *DryShaValidationCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *DryShaValidationCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *DryShaValidationCommitStatusSpecApplyConfiguration) WithKey(value string) *DryShaValidationCommitStatusSpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithEnvironments adds the given value to the Environments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environments field.
func (b *DryShaValidationCommitStatusSpecApplyConfiguration) WithEnvironments(values ...*DryShaValidationEnvironmentApplyConfiguration) *DryShaValidationCommitStatusSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironments")
		}
		b.Environments = append(b.Environments, *values[i])
	}
	return b
}

// WithLookbackLimit sets the LookbackLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LookbackLimit field is set to the value of the last call.
func (b *DryShaValidationCommitStatusSpecApplyConfiguration) WithLookbackLimit(value int32) *DryShaValidationCommitStatusSpecApplyConfiguration {
	b.LookbackLimit = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *DryShaValidationCommitStatusSpecApplyConfiguration) WithURL(value *URLConfigApplyConfiguration) *DryShaValidationCommitStatusSpecApplyConfiguration {
	b.URL = value
	return b
}
