/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ExponentialFailureApplyConfiguration represents a declarative configuration of the ExponentialFailure type for use
// with apply.
//
// ExponentialFailure defines an exponential backoff rate limiter configuration.
//
// This rate limiter increases the delay exponentially with each consecutive failure, starting at
// BaseDelay and capping at MaxDelay. This is useful for backing off when operations fail repeatedly,
// reducing load on external systems while they recover. The delay doubles with each failure until
// reaching the maximum.
//
// See https://pkg.go.dev/k8s.io/client-go/util/workqueue#NewTypedItemExponentialFailureRateLimiter
type ExponentialFailureApplyConfiguration struct {
	// BaseDelay is the initial delay after the first failure. Subsequent failures will exponentially
	// increase this delay (2x, 4x, 8x, etc.) until MaxDelay is reached.
	// Format follows Go's time.Duration syntax (e.g., "1s" for 1 second).
	BaseDelay *v1.Duration `json:"baseDelay,omitempty"`
	// MaxDelay is the maximum delay between retry attempts. Once the exponential backoff reaches
	// this value, all subsequent retries will use this delay.
	// Format follows Go's time.Duration syntax (e.g., "1m" for 1 minute).
	MaxDelay *v1.Duration `json:"maxDelay,omitempty"`
}

// ExponentialFailureApplyConfiguration constructs a declarative configuration of the ExponentialFailure type for use with
// apply.
func ExponentialFailure() *ExponentialFailureApplyConfiguration {
	return &ExponentialFailureApplyConfiguration{}
}

// WithBaseDelay sets the BaseDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseDelay field is set to the value of the last call.
func (b *ExponentialFailureApplyConfiguration) WithBaseDelay(value v1.Duration) *ExponentialFailureApplyConfiguration {
	b.BaseDelay = &value
	return b
}

// WithMaxDelay sets the MaxDelay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxDelay field is set to the value of the last call.
func (b *ExponentialFailureApplyConfiguration) WithMaxDelay(value v1.Duration) *ExponentialFailureApplyConfiguration {
	b.MaxDelay = &value
	return b
}
