/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// ForgejoApplyConfiguration represents a declarative configuration of the Forgejo type for use
// with apply.
//
// Forgejo is a Forgejo SCM provider configuration. It is used to configure the Forgejo settings.
type ForgejoApplyConfiguration struct {
	// Domain is the Forgejo domain, such as "codeberg.org" or "forgejo.mycompany.com".
	// There is no default domain since Forgejo is not a service like Gitlab or Github.
	Domain *string `json:"domain,omitempty"`
}

// ForgejoApplyConfiguration constructs a declarative configuration of the Forgejo type for use with
// apply.
func Forgejo() *ForgejoApplyConfiguration {
	return &ForgejoApplyConfiguration{}
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *ForgejoApplyConfiguration) WithDomain(value string) *ForgejoApplyConfiguration {
	b.Domain = &value
	return b
}
