/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// ForgejoRepoApplyConfiguration represents a declarative configuration of the ForgejoRepo type for use
// with apply.
//
// ForgejoRepo is a repository in Forgejo, identified by its owner and name.
type ForgejoRepoApplyConfiguration struct {
	// Owner is the owner of the repository.
	Owner *string `json:"owner,omitempty"`
	// Name is the name of the repository.
	Name *string `json:"name,omitempty"`
}

// ForgejoRepoApplyConfiguration constructs a declarative configuration of the ForgejoRepo type for use with
// apply.
func ForgejoRepo() *ForgejoRepoApplyConfiguration {
	return &ForgejoRepoApplyConfiguration{}
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *ForgejoRepoApplyConfiguration) WithOwner(value string) *ForgejoRepoApplyConfiguration {
	b.Owner = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ForgejoRepoApplyConfiguration) WithName(value string) *ForgejoRepoApplyConfiguration {
	b.Name = &value
	return b
}
