/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
)

// GateEnvironmentCommitStatusApplyConfiguration represents a declarative configuration of the GateEnvironmentCommitStatus type for use
// with apply.
//
// GateEnvironmentCommitStatus mirrors per-environment child CommitStatus report fields
// (phase, description, url, reportedSha). Used on gate CR status.environments[] only — not embedded in CommitStatusSpec.
type GateEnvironmentCommitStatusApplyConfiguration struct {
	// Phase mirrors child CommitStatus.spec.phase.
	Phase *apiv1alpha1.CommitStatusPhase `json:"phase,omitempty"`
	// Description mirrors child CommitStatus.spec.description.
	Description *string `json:"description,omitempty"`
	// Url mirrors child CommitStatus.spec.url.
	Url *string `json:"url,omitempty"`
	// ReportedSha is the hydrated SHA the child CommitStatus is attached to (CommitStatus.spec.sha).
	// Semantics depend on the parent gate (proposed vs active hydrated SHA).
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	ReportedSha *string `json:"reportedSha,omitempty"`
}

// GateEnvironmentCommitStatusApplyConfiguration constructs a declarative configuration of the GateEnvironmentCommitStatus type for use with
// apply.
func GateEnvironmentCommitStatus() *GateEnvironmentCommitStatusApplyConfiguration {
	return &GateEnvironmentCommitStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *GateEnvironmentCommitStatusApplyConfiguration) WithPhase(value apiv1alpha1.CommitStatusPhase) *GateEnvironmentCommitStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *GateEnvironmentCommitStatusApplyConfiguration) WithDescription(value string) *GateEnvironmentCommitStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *GateEnvironmentCommitStatusApplyConfiguration) WithUrl(value string) *GateEnvironmentCommitStatusApplyConfiguration {
	b.Url = &value
	return b
}

// WithReportedSha sets the ReportedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportedSha field is set to the value of the last call.
func (b *GateEnvironmentCommitStatusApplyConfiguration) WithReportedSha(value string) *GateEnvironmentCommitStatusApplyConfiguration {
	b.ReportedSha = &value
	return b
}
