/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// GitCommitVerificationGPGApplyConfiguration represents a declarative configuration of the GitCommitVerificationGPG type for use
// with apply.
//
// GitCommitVerificationGPG holds the GPG public keys a commit signature is trusted against.
type GitCommitVerificationGPGApplyConfiguration struct {
	// PublicKeys are the keys a signature must verify against. A commit signed by a key outside this
	// set is reported as unverified, so the list is the complete trust anchor for this validation.
	PublicKeys []GitCommitVerificationGPGPublicKeyApplyConfiguration `json:"publicKeys,omitempty"`
}

// GitCommitVerificationGPGApplyConfiguration constructs a declarative configuration of the GitCommitVerificationGPG type for use with
// apply.
func GitCommitVerificationGPG() *GitCommitVerificationGPGApplyConfiguration {
	return &GitCommitVerificationGPGApplyConfiguration{}
}

// WithPublicKeys adds the given value to the PublicKeys field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PublicKeys field.
func (b *GitCommitVerificationGPGApplyConfiguration) WithPublicKeys(values ...*GitCommitVerificationGPGPublicKeyApplyConfiguration) *GitCommitVerificationGPGApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPublicKeys")
		}
		b.PublicKeys = append(b.PublicKeys, *values[i])
	}
	return b
}
