/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// GitCommitVerificationGPGPublicKeyApplyConfiguration represents a declarative configuration of the GitCommitVerificationGPGPublicKey type for use
// with apply.
//
// GitCommitVerificationGPGPublicKey is a single trusted GPG public key.
type GitCommitVerificationGPGPublicKeyApplyConfiguration struct {
	// Armored is the ASCII-armored public key, as produced by `gpg --armor --export <fingerprint>`.
	Armored *string `json:"armored,omitempty"`
}

// GitCommitVerificationGPGPublicKeyApplyConfiguration constructs a declarative configuration of the GitCommitVerificationGPGPublicKey type for use with
// apply.
func GitCommitVerificationGPGPublicKey() *GitCommitVerificationGPGPublicKeyApplyConfiguration {
	return &GitCommitVerificationGPGPublicKeyApplyConfiguration{}
}

// WithArmored sets the Armored field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Armored field is set to the value of the last call.
func (b *GitCommitVerificationGPGPublicKeyApplyConfiguration) WithArmored(value string) *GitCommitVerificationGPGPublicKeyApplyConfiguration {
	b.Armored = &value
	return b
}
