/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// GitCommitStatusEnvironmentStatusApplyConfiguration represents a declarative configuration of the GitCommitStatusEnvironmentStatus type for use
// with apply.
//
// GitCommitStatusEnvironmentStatus defines the observed validation status for a specific environment.
type GitCommitStatusEnvironmentStatusApplyConfiguration struct {
	// Branch is the environment branch name being validated.
	Branch *string `json:"branch,omitempty"`
	// ProposedHydratedSha is the proposed hydrated commit SHA where the validation result is reported.
	// This comes from the PromotionStrategy's environment status.
	// The CommitStatus resource is created with this SHA, allowing the PromotionStrategy to gate
	// promotions based on the validation of the ACTIVE commit.
	// May be empty if the PromotionStrategy hasn't reconciled yet.
	ProposedHydratedSha *string `json:"proposedHydratedSha,omitempty"`
	// ActiveHydratedSha is the currently active (deployed) hydrated commit SHA that was validated.
	// This comes from the PromotionStrategy's environment status.
	// The expression is evaluated against THIS commit's data, not the proposed commit.
	// May be empty if the PromotionStrategy hasn't reconciled yet.
	ActiveHydratedSha *string `json:"activeHydratedSha,omitempty"`
	// TargetedSha is the commit SHA that was actually validated by the expression.
	// This will match either ProposedHydratedSha or ActiveHydratedSha depending on
	// the Target setting ("proposed" or "active").
	// This field clarifies which commit's data was used in the expression evaluation.
	TargetedSha *string `json:"targetedSha,omitempty"`
	// Phase represents the current validation state of the commit.
	// - "pending": validation has not completed, commit data is not yet available, or SHAs are empty
	// - "success": expression evaluated to true, validation passed
	// - "failure": expression evaluated to false, validation failed, or expression compilation failed
	Phase *string `json:"phase,omitempty"`
	// ExpressionResult contains the boolean result of the expression evaluation.
	// Only set when the expression successfully evaluates to a boolean.
	// nil indicates the expression has not yet been evaluated, failed to compile, or failed to evaluate.
	ExpressionResult *bool `json:"expressionResult,omitempty"`
}

// GitCommitStatusEnvironmentStatusApplyConfiguration constructs a declarative configuration of the GitCommitStatusEnvironmentStatus type for use with
// apply.
func GitCommitStatusEnvironmentStatus() *GitCommitStatusEnvironmentStatusApplyConfiguration {
	return &GitCommitStatusEnvironmentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *GitCommitStatusEnvironmentStatusApplyConfiguration) WithBranch(value string) *GitCommitStatusEnvironmentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithProposedHydratedSha sets the ProposedHydratedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProposedHydratedSha field is set to the value of the last call.
func (b *GitCommitStatusEnvironmentStatusApplyConfiguration) WithProposedHydratedSha(value string) *GitCommitStatusEnvironmentStatusApplyConfiguration {
	b.ProposedHydratedSha = &value
	return b
}

// WithActiveHydratedSha sets the ActiveHydratedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveHydratedSha field is set to the value of the last call.
func (b *GitCommitStatusEnvironmentStatusApplyConfiguration) WithActiveHydratedSha(value string) *GitCommitStatusEnvironmentStatusApplyConfiguration {
	b.ActiveHydratedSha = &value
	return b
}

// WithTargetedSha sets the TargetedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetedSha field is set to the value of the last call.
func (b *GitCommitStatusEnvironmentStatusApplyConfiguration) WithTargetedSha(value string) *GitCommitStatusEnvironmentStatusApplyConfiguration {
	b.TargetedSha = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *GitCommitStatusEnvironmentStatusApplyConfiguration) WithPhase(value string) *GitCommitStatusEnvironmentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithExpressionResult sets the ExpressionResult field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpressionResult field is set to the value of the last call.
func (b *GitCommitStatusEnvironmentStatusApplyConfiguration) WithExpressionResult(value bool) *GitCommitStatusEnvironmentStatusApplyConfiguration {
	b.ExpressionResult = &value
	return b
}
