/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// GitCommitStatusStatusApplyConfiguration represents a declarative configuration of the GitCommitStatusStatus type for use
// with apply.
//
// GitCommitStatusStatus defines the observed state of GitCommitStatus.
type GitCommitStatusStatusApplyConfiguration struct {
	// Environments holds the validation results for each environment where this validation applies.
	// Each entry corresponds to an environment from the PromotionStrategy where the Key matches
	// either global or environment-specific proposedCommitStatuses.
	//
	// The controller validates the commit specified by Target ("active" or "proposed")
	// but the CommitStatus is always reported on the PROPOSED commit for promotion gating.
	// Each environment entry tracks both the ProposedHydratedSha (where status is reported) and the
	// ActiveHydratedSha, with TargetedSha indicating which one was actually evaluated.
	Environments []GitCommitStatusEnvironmentStatusApplyConfiguration `json:"environments,omitempty"`
	// Conditions represent the latest available observations of the GitCommitStatus's state.
	// Standard condition types include "Ready" which aggregates the status of all environments.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// GitCommitStatusStatusApplyConfiguration constructs a declarative configuration of the GitCommitStatusStatus type for use with
// apply.
func GitCommitStatusStatus() *GitCommitStatusStatusApplyConfiguration {
	return &GitCommitStatusStatusApplyConfiguration{}
}

// WithEnvironments adds the given value to the Environments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environments field.
func (b *GitCommitStatusStatusApplyConfiguration) WithEnvironments(values ...*GitCommitStatusEnvironmentStatusApplyConfiguration) *GitCommitStatusStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironments")
		}
		b.Environments = append(b.Environments, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *GitCommitStatusStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *GitCommitStatusStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
