/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// GitHubWebhookReceiverConfigurationApplyConfiguration represents a declarative configuration of the GitHubWebhookReceiverConfiguration type for use
// with apply.
//
// GitHubWebhookReceiverConfiguration defines GitHub-specific webhook receiver configuration.
type GitHubWebhookReceiverConfigurationApplyConfiguration struct {
	// SecretRef references a Kubernetes Secret in the controller's namespace that contains
	// the GitHub webhook signing secret. The Secret must have a key named "webhookSecret"
	// whose value is the signing secret configured in the GitHub App or repository webhook
	// settings.
	//
	// When this field is set, the webhook receiver validates the X-Hub-Signature-256 header
	// on every incoming GitHub webhook request using HMAC-SHA256. Requests with a missing or
	// invalid signature are rejected with HTTP 401.
	//
	// When this field is absent, signature validation is skipped and all GitHub webhook
	// requests are accepted without verification.
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// GitHubWebhookReceiverConfigurationApplyConfiguration constructs a declarative configuration of the GitHubWebhookReceiverConfiguration type for use with
// apply.
func GitHubWebhookReceiverConfiguration() *GitHubWebhookReceiverConfigurationApplyConfiguration {
	return &GitHubWebhookReceiverConfigurationApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *GitHubWebhookReceiverConfigurationApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *GitHubWebhookReceiverConfigurationApplyConfiguration {
	b.SecretRef = &value
	return b
}
