/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// GitHubApplyConfiguration represents a declarative configuration of the GitHub type for use
// with apply.
//
// GitHub is a GitHub SCM provider configuration. It is used to configure the GitHub settings.
type GitHubApplyConfiguration struct {
	// Domain is the GitHub domain, such as "github.mycompany.com". If using the default GitHub domain, leave this field
	// empty.
	Domain *string `json:"domain,omitempty"`
	// AppID is the GitHub App ID.
	AppID *int64 `json:"appID,omitempty"`
	// InstallationID is the GitHub App Installation ID. If you want to use this ScmProvider for multiple
	// GitHub orgs, do not specify this field. The installation ID will be inferred from the repo owner
	// when needed.
	InstallationID *int64 `json:"installationID,omitempty"`
	// WebhookSecretRef references a Kubernetes Secret that contains the GitHub webhook signing secret
	// used to validate the X-Hub-Signature-256 header on incoming webhook deliveries.
	// The Secret must have a key named "webhookSecret" whose value is the signing secret
	// configured in the GitHub App or repository webhook settings.
	//
	// For a namespaced ScmProvider the Secret must be in the same namespace as the ScmProvider.
	// For a ClusterScmProvider the Secret must be in the controller's namespace.
	//
	// When set, the webhook receiver rejects requests with a missing or invalid signature (HTTP 401).
	// When absent, signature verification is skipped and all requests are accepted.
	WebhookSecretRef *v1.LocalObjectReference `json:"webhookSecretRef,omitempty"`
}

// GitHubApplyConfiguration constructs a declarative configuration of the GitHub type for use with
// apply.
func GitHub() *GitHubApplyConfiguration {
	return &GitHubApplyConfiguration{}
}

// WithDomain sets the Domain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Domain field is set to the value of the last call.
func (b *GitHubApplyConfiguration) WithDomain(value string) *GitHubApplyConfiguration {
	b.Domain = &value
	return b
}

// WithAppID sets the AppID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppID field is set to the value of the last call.
func (b *GitHubApplyConfiguration) WithAppID(value int64) *GitHubApplyConfiguration {
	b.AppID = &value
	return b
}

// WithInstallationID sets the InstallationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstallationID field is set to the value of the last call.
func (b *GitHubApplyConfiguration) WithInstallationID(value int64) *GitHubApplyConfiguration {
	b.InstallationID = &value
	return b
}

// WithWebhookSecretRef sets the WebhookSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookSecretRef field is set to the value of the last call.
func (b *GitHubApplyConfiguration) WithWebhookSecretRef(value v1.LocalObjectReference) *GitHubApplyConfiguration {
	b.WebhookSecretRef = &value
	return b
}
