/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

// GitNoteRetryApplyConfiguration represents a declarative configuration of the GitNoteRetry type for use
// with apply.
//
// GitNoteRetry is how PromotionStrategy re-enqueues ChangeTransferPolicies whose
// effective dry SHA lags a sibling while waiting for a hydrator git note (SCMs
// do not webhook notes pushes). After maxAttempts delayed nudges, retry falls
// through to changeTransferPolicy.workQueue.requeueDuration.
type GitNoteRetryApplyConfiguration struct {
	// MaxAttempts is the number of delayed re-enqueues for one unchanged
	// disagreement after the first immediate nudge. Must be at least 1.
	MaxAttempts *int `json:"maxAttempts,omitempty"`
	// ExponentialFailure is the backoff between delayed nudges (same knobs as
	// WorkQueue's exponentialFailure rate limiter). Delay for delayed attempt i
	// (0-based) is min(baseDelay * 2^i, maxDelay).
	ExponentialFailure *ExponentialFailureApplyConfiguration `json:"exponentialFailure,omitempty"`
}

// GitNoteRetryApplyConfiguration constructs a declarative configuration of the GitNoteRetry type for use with
// apply.
func GitNoteRetry() *GitNoteRetryApplyConfiguration {
	return &GitNoteRetryApplyConfiguration{}
}

// WithMaxAttempts sets the MaxAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxAttempts field is set to the value of the last call.
func (b *GitNoteRetryApplyConfiguration) WithMaxAttempts(value int) *GitNoteRetryApplyConfiguration {
	b.MaxAttempts = &value
	return b
}

// WithExponentialFailure sets the ExponentialFailure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExponentialFailure field is set to the value of the last call.
func (b *GitNoteRetryApplyConfiguration) WithExponentialFailure(value *ExponentialFailureApplyConfiguration) *GitNoteRetryApplyConfiguration {
	b.ExponentialFailure = value
	return b
}
