/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// MergeSignalsApplyConfiguration represents a declarative configuration of the MergeSignals type for use
// with apply.
//
// MergeSignals defines the comments and labels to post on a pull request to
// delegate merging to an external system (e.g. Prow/Tide).
type MergeSignalsApplyConfiguration struct {
	// Comments lists the comments to post on the PR (e.g. "/lgtm", "/approve").
	Comments []string `json:"comments,omitempty"`
	// Labels lists the labels to add to the PR (e.g. "lgtm", "approved").
	Labels []string `json:"labels,omitempty"`
}

// MergeSignalsApplyConfiguration constructs a declarative configuration of the MergeSignals type for use with
// apply.
func MergeSignals() *MergeSignalsApplyConfiguration {
	return &MergeSignalsApplyConfiguration{}
}

// WithComments adds the given value to the Comments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Comments field.
func (b *MergeSignalsApplyConfiguration) WithComments(values ...string) *MergeSignalsApplyConfiguration {
	for i := range values {
		b.Comments = append(b.Comments, values[i])
	}
	return b
}

// WithLabels adds the given value to the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Labels field.
func (b *MergeSignalsApplyConfiguration) WithLabels(values ...string) *MergeSignalsApplyConfiguration {
	for i := range values {
		b.Labels = append(b.Labels, values[i])
	}
	return b
}
