/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// ModeSpecApplyConfiguration represents a declarative configuration of the ModeSpec type for use
// with apply.
//
// ModeSpec defines the operating mode for the WebRequestCommitStatus controller.
// Exactly one of Polling or Trigger must be specified.
type ModeSpecApplyConfiguration struct {
	// Polling enables interval-based polling mode.
	// The controller will poll the HTTP endpoint at the specified interval.
	Polling *PollingModeSpecApplyConfiguration `json:"polling,omitempty"`
	// Trigger enables expression-based triggering mode.
	// The controller will evaluate the expression to determine when to make HTTP requests.
	Trigger *TriggerModeSpecApplyConfiguration `json:"trigger,omitempty"`
}

// ModeSpecApplyConfiguration constructs a declarative configuration of the ModeSpec type for use with
// apply.
func ModeSpec() *ModeSpecApplyConfiguration {
	return &ModeSpecApplyConfiguration{}
}

// WithPolling sets the Polling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Polling field is set to the value of the last call.
func (b *ModeSpecApplyConfiguration) WithPolling(value *PollingModeSpecApplyConfiguration) *ModeSpecApplyConfiguration {
	b.Polling = value
	return b
}

// WithTrigger sets the Trigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Trigger field is set to the value of the last call.
func (b *ModeSpecApplyConfiguration) WithTrigger(value *TriggerModeSpecApplyConfiguration) *ModeSpecApplyConfiguration {
	b.Trigger = value
	return b
}
