/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// NotificationDeliveryStatusApplyConfiguration represents a declarative configuration of the NotificationDeliveryStatus type for use
// with apply.
//
// NotificationDeliveryStatus records the outcome of a single delivery attempt.
type NotificationDeliveryStatusApplyConfiguration struct {
	// Time is when the delivery attempt occurred.
	Time *v1.Time `json:"time,omitempty"`
	// EventID is the stable identifier of the event that was delivered.
	EventID *string `json:"eventID,omitempty"`
	// ResponseStatus is the HTTP status code returned by the receiver, or 0 if no response
	// was received (for example on connection or timeout errors).
	ResponseStatus *int32 `json:"responseStatus,omitempty"`
}

// NotificationDeliveryStatusApplyConfiguration constructs a declarative configuration of the NotificationDeliveryStatus type for use with
// apply.
func NotificationDeliveryStatus() *NotificationDeliveryStatusApplyConfiguration {
	return &NotificationDeliveryStatusApplyConfiguration{}
}

// WithTime sets the Time field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Time field is set to the value of the last call.
func (b *NotificationDeliveryStatusApplyConfiguration) WithTime(value v1.Time) *NotificationDeliveryStatusApplyConfiguration {
	b.Time = &value
	return b
}

// WithEventID sets the EventID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventID field is set to the value of the last call.
func (b *NotificationDeliveryStatusApplyConfiguration) WithEventID(value string) *NotificationDeliveryStatusApplyConfiguration {
	b.EventID = &value
	return b
}

// WithResponseStatus sets the ResponseStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResponseStatus field is set to the value of the last call.
func (b *NotificationDeliveryStatusApplyConfiguration) WithResponseStatus(value int32) *NotificationDeliveryStatusApplyConfiguration {
	b.ResponseStatus = &value
	return b
}
