/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// OAuth2AuthSecretRefApplyConfiguration represents a declarative configuration of the OAuth2AuthSecretRef type for use
// with apply.
//
// OAuth2AuthSecretRef references a secret for OAuth2 authentication.
type OAuth2AuthSecretRefApplyConfiguration struct {
	// Name of the secret.
	Name *string `json:"name,omitempty"`
	// ClientIDKey is the key in the secret containing the client ID.
	// Defaults to "clientID".
	ClientIDKey *string `json:"clientIDKey,omitempty"`
	// ClientSecretKey is the key in the secret containing the client secret.
	// Defaults to "clientSecret".
	ClientSecretKey *string `json:"clientSecretKey,omitempty"`
}

// OAuth2AuthSecretRefApplyConfiguration constructs a declarative configuration of the OAuth2AuthSecretRef type for use with
// apply.
func OAuth2AuthSecretRef() *OAuth2AuthSecretRefApplyConfiguration {
	return &OAuth2AuthSecretRefApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OAuth2AuthSecretRefApplyConfiguration) WithName(value string) *OAuth2AuthSecretRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithClientIDKey sets the ClientIDKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientIDKey field is set to the value of the last call.
func (b *OAuth2AuthSecretRefApplyConfiguration) WithClientIDKey(value string) *OAuth2AuthSecretRefApplyConfiguration {
	b.ClientIDKey = &value
	return b
}

// WithClientSecretKey sets the ClientSecretKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecretKey field is set to the value of the last call.
func (b *OAuth2AuthSecretRefApplyConfiguration) WithClientSecretKey(value string) *OAuth2AuthSecretRefApplyConfiguration {
	b.ClientSecretKey = &value
	return b
}
