/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PollingModeSpecApplyConfiguration represents a declarative configuration of the PollingModeSpec type for use
// with apply.
//
// PollingModeSpec defines interval-based polling configuration.
type PollingModeSpecApplyConfiguration struct {
	// Interval controls how often to retry the HTTP request while in pending state.
	// When reportOn is "proposed": stops polling after success for a given SHA.
	// When reportOn is "active": always polls at this interval.
	Interval *v1.Duration `json:"interval,omitempty"`
}

// PollingModeSpecApplyConfiguration constructs a declarative configuration of the PollingModeSpec type for use with
// apply.
func PollingModeSpec() *PollingModeSpecApplyConfiguration {
	return &PollingModeSpecApplyConfiguration{}
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *PollingModeSpecApplyConfiguration) WithInterval(value v1.Duration) *PollingModeSpecApplyConfiguration {
	b.Interval = &value
	return b
}
