/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// PreviousEnvEnvironmentApplyConfiguration represents a declarative configuration of the PreviousEnvEnvironment type for use
// with apply.
//
// PreviousEnvEnvironment defines an environment that needs previous-environment checking.
type PreviousEnvEnvironmentApplyConfiguration struct {
	// Branch is the name of the environment branch.
	Branch *string `json:"branch,omitempty"`
	// ActiveCommitStatuses from the PromotionStrategy spec for this environment.
	// These are the commit statuses that must pass before promotion can proceed.
	ActiveCommitStatuses []CommitStatusSelectorApplyConfiguration `json:"activeCommitStatuses,omitempty"`
}

// PreviousEnvEnvironmentApplyConfiguration constructs a declarative configuration of the PreviousEnvEnvironment type for use with
// apply.
func PreviousEnvEnvironment() *PreviousEnvEnvironmentApplyConfiguration {
	return &PreviousEnvEnvironmentApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *PreviousEnvEnvironmentApplyConfiguration) WithBranch(value string) *PreviousEnvEnvironmentApplyConfiguration {
	b.Branch = &value
	return b
}

// WithActiveCommitStatuses adds the given value to the ActiveCommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActiveCommitStatuses field.
func (b *PreviousEnvEnvironmentApplyConfiguration) WithActiveCommitStatuses(values ...*CommitStatusSelectorApplyConfiguration) *PreviousEnvEnvironmentApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithActiveCommitStatuses")
		}
		b.ActiveCommitStatuses = append(b.ActiveCommitStatuses, *values[i])
	}
	return b
}
