/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// PreviousEnvironmentURLConfigApplyConfiguration represents a declarative configuration of the PreviousEnvironmentURLConfig type for use
// with apply.
//
// PreviousEnvironmentURLConfig is a Go text/template rendered to produce the commit status URL.
type PreviousEnvironmentURLConfigApplyConfiguration struct {
	// Template is a go text template and receives .PromotionStrategy, .PreviousEnvironmentBranch,
	// .Sha, and .AggregatedStatuses variables. A function called urlQueryEscape is available to
	// escape url query parameters.
	//
	// Example:
	//
	// {{ printf "https://argocd.example.com/applications/%s/%s?view=GitOps+Promoter&promotionstrategy=%s" .PromotionStrategy.Namespace .PromotionStrategy.Name (urlQueryEscape (printf "%s/%s" .PromotionStrategy.Namespace .PromotionStrategy.Name)) }}
	Template *string `json:"template,omitempty"`
	// Options sets options for the template, e.g. "missingkey=error". See the text/template
	// documentation for the full list of options.
	Options []string `json:"options,omitempty"`
}

// PreviousEnvironmentURLConfigApplyConfiguration constructs a declarative configuration of the PreviousEnvironmentURLConfig type for use with
// apply.
func PreviousEnvironmentURLConfig() *PreviousEnvironmentURLConfigApplyConfiguration {
	return &PreviousEnvironmentURLConfigApplyConfiguration{}
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *PreviousEnvironmentURLConfigApplyConfiguration) WithTemplate(value string) *PreviousEnvironmentURLConfigApplyConfiguration {
	b.Template = &value
	return b
}

// WithOptions adds the given value to the Options field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Options field.
func (b *PreviousEnvironmentURLConfigApplyConfiguration) WithOptions(values ...string) *PreviousEnvironmentURLConfigApplyConfiguration {
	for i := range values {
		b.Options = append(b.Options, values[i])
	}
	return b
}
