/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// PreviousEnvironmentCommitStatusSpecApplyConfiguration represents a declarative configuration of the PreviousEnvironmentCommitStatusSpec type for use
// with apply.
//
// PreviousEnvironmentCommitStatusSpec defines the desired state of PreviousEnvironmentCommitStatus.
// This resource is created by the PromotionStrategy controller to manage previous-environment
// commit status checks. It is an internal resource and should not be created by users directly.
type PreviousEnvironmentCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef is a reference to the parent PromotionStrategy.
	// The controller gets RepositoryReference from the CTPs when creating CommitStatuses.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Environments lists the environments to monitor for previous-environment checks.
	// This is derived from the PromotionStrategy's environments configuration.
	Environments []PreviousEnvEnvironmentApplyConfiguration `json:"environments,omitempty"`
}

// PreviousEnvironmentCommitStatusSpecApplyConfiguration constructs a declarative configuration of the PreviousEnvironmentCommitStatusSpec type for use with
// apply.
func PreviousEnvironmentCommitStatusSpec() *PreviousEnvironmentCommitStatusSpecApplyConfiguration {
	return &PreviousEnvironmentCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *PreviousEnvironmentCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *PreviousEnvironmentCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithEnvironments adds the given value to the Environments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environments field.
func (b *PreviousEnvironmentCommitStatusSpecApplyConfiguration) WithEnvironments(values ...*PreviousEnvEnvironmentApplyConfiguration) *PreviousEnvironmentCommitStatusSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironments")
		}
		b.Environments = append(b.Environments, *values[i])
	}
	return b
}
