/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// PromotionStrategySpecApplyConfiguration represents a declarative configuration of the PromotionStrategySpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// PromotionStrategySpec defines the desired state of PromotionStrategy
type PromotionStrategySpecApplyConfiguration struct {
	// RepositoryReference indicates what repository to promote commits in.
	RepositoryReference *ObjectReferenceApplyConfiguration `json:"gitRepositoryRef,omitempty"`
	// ActiveCommitStatuses are commit statuses describing an actively running dry commit. If an active commit status
	// is failing for an environment, subsequent environments will not deploy the failing commit.
	//
	// The commit statuses specified in this field apply to all environments in the promotion sequence. You can also
	// specify commit statuses for individual environments in the `environments` field.
	ActiveCommitStatuses []CommitStatusSelectorApplyConfiguration `json:"activeCommitStatuses,omitempty"`
	// ProposedCommitStatuses are commit statuses describing a proposed dry commit, i.e. one that is not yet running
	// in a live environment. If a proposed commit status is failing for a given environment, the dry commit will not
	// be promoted to that environment.
	//
	// The commit statuses specified in this field apply to all environments in the promotion sequence. You can also
	// specify commit statuses for individual environments in the `environments` field.
	ProposedCommitStatuses []CommitStatusSelectorApplyConfiguration `json:"proposedCommitStatuses,omitempty"`
	// Environments is the sequence of environments that a dry commit will be promoted through.
	Environments []EnvironmentApplyConfiguration `json:"environments,omitempty"`
}

// PromotionStrategySpecApplyConfiguration constructs a declarative configuration of the PromotionStrategySpec type for use with
// apply.
func PromotionStrategySpec() *PromotionStrategySpecApplyConfiguration {
	return &PromotionStrategySpecApplyConfiguration{}
}

// WithRepositoryReference sets the RepositoryReference field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositoryReference field is set to the value of the last call.
func (b *PromotionStrategySpecApplyConfiguration) WithRepositoryReference(value *ObjectReferenceApplyConfiguration) *PromotionStrategySpecApplyConfiguration {
	b.RepositoryReference = value
	return b
}

// WithActiveCommitStatuses adds the given value to the ActiveCommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ActiveCommitStatuses field.
func (b *PromotionStrategySpecApplyConfiguration) WithActiveCommitStatuses(values ...*CommitStatusSelectorApplyConfiguration) *PromotionStrategySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithActiveCommitStatuses")
		}
		b.ActiveCommitStatuses = append(b.ActiveCommitStatuses, *values[i])
	}
	return b
}

// WithProposedCommitStatuses adds the given value to the ProposedCommitStatuses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ProposedCommitStatuses field.
func (b *PromotionStrategySpecApplyConfiguration) WithProposedCommitStatuses(values ...*CommitStatusSelectorApplyConfiguration) *PromotionStrategySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProposedCommitStatuses")
		}
		b.ProposedCommitStatuses = append(b.ProposedCommitStatuses, *values[i])
	}
	return b
}

// WithEnvironments adds the given value to the Environments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environments field.
func (b *PromotionStrategySpecApplyConfiguration) WithEnvironments(values ...*EnvironmentApplyConfiguration) *PromotionStrategySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironments")
		}
		b.Environments = append(b.Environments, *values[i])
	}
	return b
}
