/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// PromotionStrategyConfigurationApplyConfiguration represents a declarative configuration of the PromotionStrategyConfiguration type for use
// with apply.
//
// PromotionStrategyConfiguration defines the configuration for the PromotionStrategy controller.
//
// This configuration controls how the PromotionStrategy controller processes reconciliation
// requests, including requeue intervals, concurrency limits, and rate limiting behavior.
type PromotionStrategyConfigurationApplyConfiguration struct {
	// WorkQueue contains the work queue configuration for the PromotionStrategy controller.
	// This includes requeue duration, maximum concurrent reconciles, and rate limiter settings.
	WorkQueue *WorkQueueApplyConfiguration `json:"workQueue,omitempty"`
}

// PromotionStrategyConfigurationApplyConfiguration constructs a declarative configuration of the PromotionStrategyConfiguration type for use with
// apply.
func PromotionStrategyConfiguration() *PromotionStrategyConfigurationApplyConfiguration {
	return &PromotionStrategyConfigurationApplyConfiguration{}
}

// WithWorkQueue sets the WorkQueue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkQueue field is set to the value of the last call.
func (b *PromotionStrategyConfigurationApplyConfiguration) WithWorkQueue(value *WorkQueueApplyConfiguration) *PromotionStrategyConfigurationApplyConfiguration {
	b.WorkQueue = value
	return b
}
