/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PullRequestCommonStatusApplyConfiguration represents a declarative configuration of the PullRequestCommonStatus type for use
// with apply.
//
// PullRequestCommonStatus defines the common status fields for a pull request.
type PullRequestCommonStatusApplyConfiguration struct {
	// ID is the unique identifier of the pull request, set by the SCM.
	ID *string `json:"id,omitempty"`
	// State is the state of the pull request.
	State *apiv1alpha1.PullRequestState `json:"state,omitempty"`
	// PRCreationTime is the time when the pull request was created.
	PRCreationTime *v1.Time `json:"prCreationTime,omitempty"`
	// PRMergeTime is the time when the pull request was merged. This time can vary slightly from the actual merge time because
	// it is the time when the ChangeTransferPolicy controller sets the pull requests spec to merge. In the future we plan on making
	// this time more accurate by fetching the actual merge time from the SCM via the webhook this would then be updated in the git note
	// for that commit.
	PRMergeTime *v1.Time `json:"prMergeTime,omitempty"`
	// Url is the URL of the pull request.
	Url *string `json:"url,omitempty"`
	// MergedTargetSha is the SHA that the target branch points at after the merge. It is a merge commit
	// only when the SCM created one; squash and fast-forward merges report the resulting commit on the
	// target branch instead. In the live pull request status it is mirrored from the PullRequest resource
	// and is empty until the merge is observed; in a History entry it is the active-branch commit the
	// entry describes.
	MergedTargetSha *string `json:"mergedTargetSha,omitempty"`
	// ExternallyMergedOrClosed indicated that the pull request was no longer open on the SCM while
	// promotion still desired it open. The PullRequest controller no longer sets this field.
	//
	// Deprecated: Use status.state merged-or-closed or unknown instead. Existing values may still
	// appear when mirrored from older PullRequest status. This field may be removed in a future API
	// revision.
	ExternallyMergedOrClosed *bool `json:"externallyMergedOrClosed,omitempty"`
}

// PullRequestCommonStatusApplyConfiguration constructs a declarative configuration of the PullRequestCommonStatus type for use with
// apply.
func PullRequestCommonStatus() *PullRequestCommonStatusApplyConfiguration {
	return &PullRequestCommonStatusApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *PullRequestCommonStatusApplyConfiguration) WithID(value string) *PullRequestCommonStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *PullRequestCommonStatusApplyConfiguration) WithState(value apiv1alpha1.PullRequestState) *PullRequestCommonStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithPRCreationTime sets the PRCreationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PRCreationTime field is set to the value of the last call.
func (b *PullRequestCommonStatusApplyConfiguration) WithPRCreationTime(value v1.Time) *PullRequestCommonStatusApplyConfiguration {
	b.PRCreationTime = &value
	return b
}

// WithPRMergeTime sets the PRMergeTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PRMergeTime field is set to the value of the last call.
func (b *PullRequestCommonStatusApplyConfiguration) WithPRMergeTime(value v1.Time) *PullRequestCommonStatusApplyConfiguration {
	b.PRMergeTime = &value
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *PullRequestCommonStatusApplyConfiguration) WithUrl(value string) *PullRequestCommonStatusApplyConfiguration {
	b.Url = &value
	return b
}

// WithMergedTargetSha sets the MergedTargetSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MergedTargetSha field is set to the value of the last call.
func (b *PullRequestCommonStatusApplyConfiguration) WithMergedTargetSha(value string) *PullRequestCommonStatusApplyConfiguration {
	b.MergedTargetSha = &value
	return b
}

// WithExternallyMergedOrClosed sets the ExternallyMergedOrClosed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternallyMergedOrClosed field is set to the value of the last call.
func (b *PullRequestCommonStatusApplyConfiguration) WithExternallyMergedOrClosed(value bool) *PullRequestCommonStatusApplyConfiguration {
	b.ExternallyMergedOrClosed = &value
	return b
}
