/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PullRequestStatusApplyConfiguration represents a declarative configuration of the PullRequestStatus type for use
// with apply.
//
// PullRequestStatus defines the observed state of PullRequest
type PullRequestStatusApplyConfiguration struct {
	// ID the id of the pull request
	ID *string `json:"id,omitempty"`
	// State of the merge request closed/merged/open
	State *apiv1alpha1.PullRequestState `json:"state,omitempty"`
	// PRCreationTime the time the PR was created
	PRCreationTime *v1.Time `json:"prCreationTime,omitempty"`
	// Url is the URL of the pull request.
	Url *string `json:"url,omitempty"`
	// ExternallyMergedOrClosed indicates that the pull request was merged or closed externally.
	// This is set to true when the pull request has an ID but is no longer found on the SCM provider.
	// When true, the State field will be empty ("") since we cannot determine if it was merged or closed.
	// The PullRequest resource will be deleted after this flag is set, but the status is preserved in
	// the owning ChangeTransferPolicy to maintain a record of the external action.
	ExternallyMergedOrClosed *bool `json:"externallyMergedOrClosed,omitempty"`
	// Conditions Represents the observations of the current state.
	Conditions []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// PullRequestStatusApplyConfiguration constructs a declarative configuration of the PullRequestStatus type for use with
// apply.
func PullRequestStatus() *PullRequestStatusApplyConfiguration {
	return &PullRequestStatusApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *PullRequestStatusApplyConfiguration) WithID(value string) *PullRequestStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *PullRequestStatusApplyConfiguration) WithState(value apiv1alpha1.PullRequestState) *PullRequestStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithPRCreationTime sets the PRCreationTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PRCreationTime field is set to the value of the last call.
func (b *PullRequestStatusApplyConfiguration) WithPRCreationTime(value v1.Time) *PullRequestStatusApplyConfiguration {
	b.PRCreationTime = &value
	return b
}

// WithUrl sets the Url field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Url field is set to the value of the last call.
func (b *PullRequestStatusApplyConfiguration) WithUrl(value string) *PullRequestStatusApplyConfiguration {
	b.Url = &value
	return b
}

// WithExternallyMergedOrClosed sets the ExternallyMergedOrClosed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExternallyMergedOrClosed field is set to the value of the last call.
func (b *PullRequestStatusApplyConfiguration) WithExternallyMergedOrClosed(value bool) *PullRequestStatusApplyConfiguration {
	b.ExternallyMergedOrClosed = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PullRequestStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *PullRequestStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
