/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// RateLimiterTypesApplyConfiguration represents a declarative configuration of the RateLimiterTypes type for use
// with apply.
//
// RateLimiterTypes defines the different algorithms available for rate limiting.
//
// Exactly one of the three rate limiter types must be specified:
// - FastSlow: Quick retry for transient errors, then slower retry for persistent failures
// - ExponentialFailure: Standard exponential backoff for repeated failures
// - Bucket: Token bucket algorithm for controlling overall request rate
//
// See https://pkg.go.dev/k8s.io/client-go/util/workqueue for implementation details.
type RateLimiterTypesApplyConfiguration struct {
	// FastSlow rate limiter provides fast retries initially, then switches to slow retries.
	// Useful for quickly retrying transient errors while backing off for persistent failures.
	FastSlow *FastSlowApplyConfiguration `json:"fastSlow,omitempty"`
	// ExponentialFailure rate limiter increases delay exponentially with each failure.
	// Standard approach for backing off when operations fail repeatedly.
	ExponentialFailure *ExponentialFailureApplyConfiguration `json:"exponentialFailure,omitempty"`
	// Bucket rate limiter uses a token bucket algorithm to control request rate.
	// Allows bursts while maintaining an average rate limit.
	Bucket *BucketApplyConfiguration `json:"bucket,omitempty"`
}

// RateLimiterTypesApplyConfiguration constructs a declarative configuration of the RateLimiterTypes type for use with
// apply.
func RateLimiterTypes() *RateLimiterTypesApplyConfiguration {
	return &RateLimiterTypesApplyConfiguration{}
}

// WithFastSlow sets the FastSlow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FastSlow field is set to the value of the last call.
func (b *RateLimiterTypesApplyConfiguration) WithFastSlow(value *FastSlowApplyConfiguration) *RateLimiterTypesApplyConfiguration {
	b.FastSlow = value
	return b
}

// WithExponentialFailure sets the ExponentialFailure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExponentialFailure field is set to the value of the last call.
func (b *RateLimiterTypesApplyConfiguration) WithExponentialFailure(value *ExponentialFailureApplyConfiguration) *RateLimiterTypesApplyConfiguration {
	b.ExponentialFailure = value
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *RateLimiterTypesApplyConfiguration) WithBucket(value *BucketApplyConfiguration) *RateLimiterTypesApplyConfiguration {
	b.Bucket = value
	return b
}
