/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// ResponseExpressionSpecApplyConfiguration represents a declarative configuration of the ResponseExpressionSpec type for use
// with apply.
//
// ResponseExpressionSpec holds the expression that extracts data from the HTTP response.
type ResponseExpressionSpecApplyConfiguration struct {
	// DataExpression is an expr expression that extracts and transforms data from the HTTP response
	// before storing it in ResponseData. This allows you to store only the fields you need instead
	// of the entire response body.
	//
	// The expression is evaluated after the HTTP request completes (for any response status) and its
	// result is stored in status.environments[].responseData. On the next reconcile that value is
	// available as the ResponseData variable, so trigger expressions can read it (e.g. to implement
	// retry-on-response-status logic) and description/URL templates can reference it.
	//
	// If this field is omitted no response data is stored (status.environments[].responseData is not updated).
	//
	// Available variables:
	// - Response.StatusCode (int): HTTP response status code
	// - Response.Body (any): parsed JSON as map[string]any, or raw string if not JSON
	// - Response.Headers (map[string][]string): HTTP response headers
	//
	// The expression must return a map/object that will be stored as ResponseData.
	//
	// Examples:
	// # Store only specific fields from response body
	// - |
	// {
	// status: Response.Body.status,
	// retryAfter: Response.Body.retryAfter,
	// message: Response.Body.message
	// }
	//
	// # Store status code and a single field
	// - |
	// {
	// statusCode: Response.StatusCode,
	// approved: Response.Body.approved
	// }
	//
	// # Extract rate limit info from headers
	// - |
	// {
	// statusCode: Response.StatusCode,
	// rateLimit: {
	// remaining: int(Response.Headers["X-RateLimit-Remaining"][0]),
	// reset: Response.Headers["X-RateLimit-Reset"][0]
	// }
	// }
	//
	// # Conditional extraction based on status code
	// - |
	// Response.StatusCode == 200 ?
	// {status: "success", data: Response.Body.result} :
	// {status: "error", error: Response.Body.error}
	DataExpression *string `json:"dataExpression,omitempty"`
}

// ResponseExpressionSpecApplyConfiguration constructs a declarative configuration of the ResponseExpressionSpec type for use with
// apply.
func ResponseExpressionSpec() *ResponseExpressionSpecApplyConfiguration {
	return &ResponseExpressionSpecApplyConfiguration{}
}

// WithDataExpression sets the DataExpression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataExpression field is set to the value of the last call.
func (b *ResponseExpressionSpecApplyConfiguration) WithDataExpression(value string) *ResponseExpressionSpecApplyConfiguration {
	b.DataExpression = &value
	return b
}
