/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// ResponseOutputSpecApplyConfiguration represents a declarative configuration of the ResponseOutputSpec type for use
// with apply.
//
// ResponseOutputSpec holds the expression that extracts data from the HTTP response into ResponseOutput.
type ResponseOutputSpecApplyConfiguration struct {
	// Output holds the expression that extracts and transforms data from the HTTP response.
	// The expression is evaluated after the HTTP request completes (for any response status) and its
	// result is stored in status.environments[].responseOutput. On the next reconcile that value is
	// available as the ResponseOutput variable. Available in the expression: Response.StatusCode,
	// Response.Body (parsed JSON or raw string), Response.Headers. The expression must return a map/object.
	Output *OutputSpecApplyConfiguration `json:"output,omitempty"`
}

// ResponseOutputSpecApplyConfiguration constructs a declarative configuration of the ResponseOutputSpec type for use with
// apply.
func ResponseOutputSpec() *ResponseOutputSpecApplyConfiguration {
	return &ResponseOutputSpecApplyConfiguration{}
}

// WithOutput sets the Output field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Output field is set to the value of the last call.
func (b *ResponseOutputSpecApplyConfiguration) WithOutput(value *OutputSpecApplyConfiguration) *ResponseOutputSpecApplyConfiguration {
	b.Output = value
	return b
}
