/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

// RestoreActiveCommitSpecApplyConfiguration represents a declarative configuration of the RestoreActiveCommitSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// RestoreActiveCommitSpec defines the desired state of RestoreActiveCommit. promotionStrategyRef,
// branch, and sha are immutable: the restore runs once, and status.blockedDrySha is read from the
// active tip it moved off of, so pointing an existing RestoreActiveCommit at a different sha,
// strategy, or branch would lose track of what dry SHA it moved off. To restore something else, create a new
// RestoreActiveCommit. blockEnvironment may change.
type RestoreActiveCommitSpecApplyConfiguration struct {
	// PromotionStrategyRef selects the PromotionStrategy that owns the environment to restore.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Branch is the environment branch on that PromotionStrategy to restore. The controller resolves
	// it to the ChangeTransferPolicy the strategy created for this branch, which supplies the
	// repository, the active and proposed branches, and activePath.
	Branch *string `json:"branch,omitempty"`
	// Sha is the hydrated commit to restore onto the active branch. It must already be in the active
	// branch's history (the tip or one of its ancestors); any other commit is refused. A commit that
	// carries Promoter-restored-from is itself a restore and is refused. Once the active tip already
	// restores this sha and its note carries Promoter-restore-unblocked-at, another RestoreActiveCommit
	// for the same sha is refused until the active branch moves, and that note is left unchanged. The
	// controller writes a new commit (the commit's tree, or only activePath when the policy sets
	// one) parented on the current active tip and records a promotion-history note with
	// Promoter-restored-from. When the active branch already has that content, nothing is written.
	// The proposed branch is left as the hydrator wrote it. The ChangeTransferPolicy does not open
	// a promotion pull request that would put the active branch's dry SHA back. A pull request
	// for a different proposed dry SHA may open, but nothing is auto-merged while this
	// RestoreActiveCommit exists. Deleting it lifts that block but does not by itself propose the
	// blocked dry SHA again; see status.blockedDrySha.
	// The restore runs once. Later promotions are left alone.
	Sha *string `json:"sha,omitempty"`
	// BlockEnvironment blocks promotion for this environment while true. It defaults to true.
	// Set it to false to stamp Promoter-restore-unblocked-at on the restore commit's promotion-history
	// note and delete this object. Deleting it while the field is still true does not stamp that
	// trailer, so deleting the PromotionStrategy cannot release the block. While the active tip is
	// still a blocked restore, the ChangeTransferPolicy recreates this object (with the default true)
	// so the field can be set false again.
	BlockEnvironment *bool `json:"blockEnvironment,omitempty"`
}

// RestoreActiveCommitSpecApplyConfiguration constructs a declarative configuration of the RestoreActiveCommitSpec type for use with
// apply.
func RestoreActiveCommitSpec() *RestoreActiveCommitSpecApplyConfiguration {
	return &RestoreActiveCommitSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *RestoreActiveCommitSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *RestoreActiveCommitSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *RestoreActiveCommitSpecApplyConfiguration) WithBranch(value string) *RestoreActiveCommitSpecApplyConfiguration {
	b.Branch = &value
	return b
}

// WithSha sets the Sha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sha field is set to the value of the last call.
func (b *RestoreActiveCommitSpecApplyConfiguration) WithSha(value string) *RestoreActiveCommitSpecApplyConfiguration {
	b.Sha = &value
	return b
}

// WithBlockEnvironment sets the BlockEnvironment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BlockEnvironment field is set to the value of the last call.
func (b *RestoreActiveCommitSpecApplyConfiguration) WithBlockEnvironment(value bool) *RestoreActiveCommitSpecApplyConfiguration {
	b.BlockEnvironment = &value
	return b
}
