/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.22. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RestoreActiveCommitStatusApplyConfiguration represents a declarative configuration of the RestoreActiveCommitStatus type for use
// with apply.
//
// RestoreActiveCommitStatus defines the observed state of RestoreActiveCommit.
type RestoreActiveCommitStatusApplyConfiguration struct {
	// ObservedGeneration is the .metadata.generation that this status was reconciled from.
	// Because status is written via Server-Side Apply with ForceOwnership (which has no
	// optimistic-concurrency check), this field is the canonical way to detect stale
	// status writes: compare status.observedGeneration with metadata.generation.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// ActiveSha is the commit on the active branch after a successful restore.
	ActiveSha *string `json:"activeSha,omitempty"`
	// BlockedDrySha is the dry SHA read from hydrator.metadata on the active tip that this restore
	// moved off of. The ChangeTransferPolicy does not open a promotion pull request while its
	// proposed dry SHA still equals this value, so the blocked dry SHA is not put back. A different
	// proposed dry SHA may open a pull request, but nothing is auto-merged until spec.blockEnvironment
	// is set to false. That stamps Promoter-restore-unblocked-at and deletes this object. Deleting it
	// while the field is still true does not stamp the trailer, so the block stays. Empty when that
	// active tip had no hydrator.metadata, or when the active branch already had spec.sha's content
	// so nothing was moved off it. A
	// promotion pull request only opens when the proposed branch has a commit the
	// active branch does not already contain. The restore commit is parented on the tip it moved
	// off of, so when that tip already contains the proposed commit (a merge-commit promotion),
	// this dry SHA is not proposed again until the hydrator writes a new commit to the proposed branch.
	BlockedDrySha *string `json:"blockedDrySha,omitempty"`
	// RestoredFrom is the spec.sha this status applied. It is written in the same status update as
	// activeSha and blockedDrySha, so it alone marks the restore as done. While it matches spec.sha
	// the controller does not restore again, so a later promotion is not overwritten on resync.
	RestoredFrom *string `json:"restoredFrom,omitempty"`
	// Conditions represent the latest available observations of an object's state.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// InstanceID mirrors metadata.labels[promoter.argoproj.io/instance-id] stamped on each
	// reconcile attempt by this install's controller, including when Ready=False; omitted
	// when the resource has no instance-id label (default install).
	InstanceID *string `json:"instanceID,omitempty"`
}

// RestoreActiveCommitStatusApplyConfiguration constructs a declarative configuration of the RestoreActiveCommitStatus type for use with
// apply.
func RestoreActiveCommitStatus() *RestoreActiveCommitStatusApplyConfiguration {
	return &RestoreActiveCommitStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *RestoreActiveCommitStatusApplyConfiguration) WithObservedGeneration(value int64) *RestoreActiveCommitStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithActiveSha sets the ActiveSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveSha field is set to the value of the last call.
func (b *RestoreActiveCommitStatusApplyConfiguration) WithActiveSha(value string) *RestoreActiveCommitStatusApplyConfiguration {
	b.ActiveSha = &value
	return b
}

// WithBlockedDrySha sets the BlockedDrySha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BlockedDrySha field is set to the value of the last call.
func (b *RestoreActiveCommitStatusApplyConfiguration) WithBlockedDrySha(value string) *RestoreActiveCommitStatusApplyConfiguration {
	b.BlockedDrySha = &value
	return b
}

// WithRestoredFrom sets the RestoredFrom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestoredFrom field is set to the value of the last call.
func (b *RestoreActiveCommitStatusApplyConfiguration) WithRestoredFrom(value string) *RestoreActiveCommitStatusApplyConfiguration {
	b.RestoredFrom = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RestoreActiveCommitStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RestoreActiveCommitStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithInstanceID sets the InstanceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceID field is set to the value of the last call.
func (b *RestoreActiveCommitStatusApplyConfiguration) WithInstanceID(value string) *RestoreActiveCommitStatusApplyConfiguration {
	b.InstanceID = &value
	return b
}
