/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// ScheduledEnvironmentApplyConfiguration represents a declarative configuration of the ScheduledEnvironment type for use
// with apply.
//
// ScheduledEnvironment defines the window configuration for a single environment.
type ScheduledEnvironmentApplyConfiguration struct {
	// Branch is the name of the branch/environment you want to gate with time windows.
	// Must not start with '-', contain ':', or contain '..'.
	Branch *string `json:"branch,omitempty"`
	// Allow defines the allowed promotion windows. Promotions are allowed when the current time
	// falls inside any of these windows (OR semantics). These are combined with any global
	// spec.allow windows. If no allow windows are defined (neither here nor globally), the
	// environment operates in exclusion-only mode.
	Allow []CronWindowApplyConfiguration `json:"allow,omitempty"`
	// Exclude defines blackout periods during which promotions are blocked. Exclusions take
	// precedence over allow windows — if the current time falls inside any exclusion, promotions
	// are blocked regardless of allow windows. These are combined with any global spec.exclude
	// windows. If empty, no blackout periods are applied.
	Exclude []CronWindowApplyConfiguration `json:"exclude,omitempty"`
}

// ScheduledEnvironmentApplyConfiguration constructs a declarative configuration of the ScheduledEnvironment type for use with
// apply.
func ScheduledEnvironment() *ScheduledEnvironmentApplyConfiguration {
	return &ScheduledEnvironmentApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *ScheduledEnvironmentApplyConfiguration) WithBranch(value string) *ScheduledEnvironmentApplyConfiguration {
	b.Branch = &value
	return b
}

// WithAllow adds the given value to the Allow field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Allow field.
func (b *ScheduledEnvironmentApplyConfiguration) WithAllow(values ...*CronWindowApplyConfiguration) *ScheduledEnvironmentApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllow")
		}
		b.Allow = append(b.Allow, *values[i])
	}
	return b
}

// WithExclude adds the given value to the Exclude field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Exclude field.
func (b *ScheduledEnvironmentApplyConfiguration) WithExclude(values ...*CronWindowApplyConfiguration) *ScheduledEnvironmentApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExclude")
		}
		b.Exclude = append(b.Exclude, *values[i])
	}
	return b
}
