/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// ScheduledCommitStatusSpecApplyConfiguration represents a declarative configuration of the ScheduledCommitStatusSpec type for use
// with apply.
//
// ScheduledCommitStatusSpec defines the desired state of ScheduledCommitStatus.
type ScheduledCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef is a reference to the promotion strategy that this scheduled commit status applies to.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Key is the gate name referenced in the PromotionStrategy's proposedCommitStatuses.
	// Must be lowercase alphanumeric with hyphens, 1–63 characters (pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$).
	Key *string `json:"key,omitempty"`
	// Timezone is the default IANA timezone name used for evaluating cron expressions across all windows.
	// Individual windows may override this with their own timezone field.
	// Defaults to UTC.
	Timezone *string `json:"timezone,omitempty"`
	// Allow defines global allow windows applied to all listed environments in addition to
	// per-environment allow windows (OR semantics across all).
	Allow []CronWindowApplyConfiguration `json:"allow,omitempty"`
	// Exclude defines global exclusion windows applied to all listed environments in addition to
	// per-environment exclusions. Exclusions take precedence over allow windows.
	Exclude []CronWindowApplyConfiguration `json:"exclude,omitempty"`
	// Environments defines the list of environments to gate. Only listed environments are gated;
	// unlisted environments default to success (24/7 open). Each environment inherits global
	// allow/exclude windows and may add its own. An environment with no per-environment windows
	// is valid when global windows are defined.
	Environments []ScheduledEnvironmentApplyConfiguration `json:"environments,omitempty"`
}

// ScheduledCommitStatusSpecApplyConfiguration constructs a declarative configuration of the ScheduledCommitStatusSpec type for use with
// apply.
func ScheduledCommitStatusSpec() *ScheduledCommitStatusSpecApplyConfiguration {
	return &ScheduledCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *ScheduledCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *ScheduledCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ScheduledCommitStatusSpecApplyConfiguration) WithKey(value string) *ScheduledCommitStatusSpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithTimezone sets the Timezone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timezone field is set to the value of the last call.
func (b *ScheduledCommitStatusSpecApplyConfiguration) WithTimezone(value string) *ScheduledCommitStatusSpecApplyConfiguration {
	b.Timezone = &value
	return b
}

// WithAllow adds the given value to the Allow field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Allow field.
func (b *ScheduledCommitStatusSpecApplyConfiguration) WithAllow(values ...*CronWindowApplyConfiguration) *ScheduledCommitStatusSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllow")
		}
		b.Allow = append(b.Allow, *values[i])
	}
	return b
}

// WithExclude adds the given value to the Exclude field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Exclude field.
func (b *ScheduledCommitStatusSpecApplyConfiguration) WithExclude(values ...*CronWindowApplyConfiguration) *ScheduledCommitStatusSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExclude")
		}
		b.Exclude = append(b.Exclude, *values[i])
	}
	return b
}

// WithEnvironments adds the given value to the Environments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environments field.
func (b *ScheduledCommitStatusSpecApplyConfiguration) WithEnvironments(values ...*ScheduledEnvironmentApplyConfiguration) *ScheduledCommitStatusSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironments")
		}
		b.Environments = append(b.Environments, *values[i])
	}
	return b
}
