/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.21. DO NOT EDIT.

package v1alpha1

// ScmLabelsSpecApplyConfiguration represents a declarative configuration of the ScmLabelsSpec type for use
// with apply.
//
// ScmLabelsSpec configures dynamic SCM pull request labels via an expression.
type ScmLabelsSpecApplyConfiguration struct {
	// Expression is evaluated using the expr library (github.com/expr-lang/expr) against
	// ChangeTransferPolicy status and spec. It must return a list of SCM label name strings.
	//
	// Available variables:
	// - Status: ChangeTransferPolicy status (Proposed/Active commit statuses, branch SHAs, etc.)
	// - Spec: ChangeTransferPolicy spec (ActiveBranch, ProposedBranch, etc.)
	// - PromotionStrategy: owning PromotionStrategy spec and status when available
	//
	// Each returned label name must satisfy the same validation as PullRequest.spec.labels
	// (non-empty, max 50 characters, no newlines, max 10 labels, unique).
	Expression *string `json:"expression,omitempty"`
}

// ScmLabelsSpecApplyConfiguration constructs a declarative configuration of the ScmLabelsSpec type for use with
// apply.
func ScmLabelsSpec() *ScmLabelsSpecApplyConfiguration {
	return &ScmLabelsSpecApplyConfiguration{}
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *ScmLabelsSpecApplyConfiguration) WithExpression(value string) *ScmLabelsSpecApplyConfiguration {
	b.Expression = &value
	return b
}
