/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// SecretKeyReferenceApplyConfiguration represents a declarative configuration of the SecretKeyReference type for use
// with apply.
//
// SecretKeyReference references a specific key within a Secret in the same namespace.
type SecretKeyReferenceApplyConfiguration struct {
	// Name is the name of the Secret.
	Name *string `json:"name,omitempty"`
	// Key is the key within the Secret's data that holds the value.
	Key *string `json:"key,omitempty"`
}

// SecretKeyReferenceApplyConfiguration constructs a declarative configuration of the SecretKeyReference type for use with
// apply.
func SecretKeyReference() *SecretKeyReferenceApplyConfiguration {
	return &SecretKeyReferenceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SecretKeyReferenceApplyConfiguration) WithName(value string) *SecretKeyReferenceApplyConfiguration {
	b.Name = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *SecretKeyReferenceApplyConfiguration) WithKey(value string) *SecretKeyReferenceApplyConfiguration {
	b.Key = &value
	return b
}
