/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// SuccessSpecApplyConfiguration represents a declarative configuration of the SuccessSpec type for use
// with apply.
//
// SuccessSpec defines when the HTTP response is considered successful (commit status phase success).
type SuccessSpecApplyConfiguration struct {
	// When holds the expression evaluated against the HTTP response (expr library).
	// Variables and return types depend on spec.mode.context; see when.expression.
	When *WhenSpecApplyConfiguration `json:"when,omitempty"`
}

// SuccessSpecApplyConfiguration constructs a declarative configuration of the SuccessSpec type for use with
// apply.
func SuccessSpec() *SuccessSpecApplyConfiguration {
	return &SuccessSpecApplyConfiguration{}
}

// WithWhen sets the When field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the When field is set to the value of the last call.
func (b *SuccessSpecApplyConfiguration) WithWhen(value *WhenSpecApplyConfiguration) *SuccessSpecApplyConfiguration {
	b.When = value
	return b
}
