/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TimedCommitStatusEnvironmentsApplyConfiguration represents a declarative configuration of the TimedCommitStatusEnvironments type for use
// with apply.
//
// TimedCommitStatusEnvironments defines the branch/environment and duration to wait before reporting the gate as success.
type TimedCommitStatusEnvironmentsApplyConfiguration struct {
	// Branch is the name of the branch/environment you want to gate for the configured duration.
	Branch *string `json:"branch,omitempty"`
	// Duration is the time duration to wait before considering the commit status as success.
	// The duration should be in a format accepted by Go's time.ParseDuration function, e.g., "5m", "1h30m".
	Duration *v1.Duration `json:"duration,omitempty"`
}

// TimedCommitStatusEnvironmentsApplyConfiguration constructs a declarative configuration of the TimedCommitStatusEnvironments type for use with
// apply.
func TimedCommitStatusEnvironments() *TimedCommitStatusEnvironmentsApplyConfiguration {
	return &TimedCommitStatusEnvironmentsApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *TimedCommitStatusEnvironmentsApplyConfiguration) WithBranch(value string) *TimedCommitStatusEnvironmentsApplyConfiguration {
	b.Branch = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *TimedCommitStatusEnvironmentsApplyConfiguration) WithDuration(value v1.Duration) *TimedCommitStatusEnvironmentsApplyConfiguration {
	b.Duration = &value
	return b
}
