/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// TimedCommitStatusSpecApplyConfiguration represents a declarative configuration of the TimedCommitStatusSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// TimedCommitStatusSpec defines the desired state of TimedCommitStatus
type TimedCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef is a reference to the promotion strategy that this timed commit status applies to.
	PromotionStrategyRef *ObjectReferenceApplyConfiguration                `json:"promotionStrategyRef,omitempty"`
	Environments         []TimedCommitStatusEnvironmentsApplyConfiguration `json:"environments,omitempty"`
}

// TimedCommitStatusSpecApplyConfiguration constructs a declarative configuration of the TimedCommitStatusSpec type for use with
// apply.
func TimedCommitStatusSpec() *TimedCommitStatusSpecApplyConfiguration {
	return &TimedCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *TimedCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *TimedCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithEnvironments adds the given value to the Environments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Environments field.
func (b *TimedCommitStatusSpecApplyConfiguration) WithEnvironments(values ...*TimedCommitStatusEnvironmentsApplyConfiguration) *TimedCommitStatusSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEnvironments")
		}
		b.Environments = append(b.Environments, *values[i])
	}
	return b
}
