/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// TLSAuthApplyConfiguration represents a declarative configuration of the TLSAuth type for use
// with apply.
//
// TLSAuth defines TLS client certificate authentication (mutual TLS / mTLS).
//
// Mutual TLS authentication proves the client's identity using a certificate,
// rather than a password or token. This is configured at the TLS transport layer,
// not as an HTTP header.
//
// Use cases:
// - High-security environments requiring certificate-based authentication
// - APIs that require client certificates for access
// - Service mesh authentication
// - Zero-trust network architectures
//
// The secret must contain:
// - Client certificate (default key: "tls.crt")
// - Private key (default key: "tls.key")
// - Optional CA certificate for custom CAs (default key: "ca.crt")
//
// Example:
//
// tls:
// secretRef:
// name: my-client-cert
// certKey: tls.crt  # optional, defaults to "tls.crt"
// keyKey: tls.key   # optional, defaults to "tls.key"
// caKey: ca.crt     # optional, defaults to "ca.crt"
//
// Note: TLS auth is applied at the HTTP client transport layer, unlike other
// authentication methods which are applied as HTTP headers.
type TLSAuthApplyConfiguration struct {
	// SecretRef references a secret containing TLS certificate and key.
	// The secret should be of type kubernetes.io/tls or contain the required keys.
	SecretRef *TLSAuthSecretRefApplyConfiguration `json:"secretRef,omitempty"`
}

// TLSAuthApplyConfiguration constructs a declarative configuration of the TLSAuth type for use with
// apply.
func TLSAuth() *TLSAuthApplyConfiguration {
	return &TLSAuthApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *TLSAuthApplyConfiguration) WithSecretRef(value *TLSAuthSecretRefApplyConfiguration) *TLSAuthApplyConfiguration {
	b.SecretRef = value
	return b
}
