/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TriggerModeSpecApplyConfiguration represents a declarative configuration of the TriggerModeSpec type for use
// with apply.
//
// TriggerModeSpec defines expression-based trigger configuration.
type TriggerModeSpecApplyConfiguration struct {
	// RequeueDuration specifies how long to wait before requeuing to re-evaluate the trigger expression.
	RequeueDuration *v1.Duration `json:"requeueDuration,omitempty"`
	// When configures the boolean guard and optional output expression that control whether the HTTP request is made.
	When *WhenWithOutputSpecApplyConfiguration `json:"when,omitempty"`
	// Response optionally configures an expression that extracts data from the HTTP response into ResponseOutput.
	Response *ResponseOutputSpecApplyConfiguration `json:"response,omitempty"`
}

// TriggerModeSpecApplyConfiguration constructs a declarative configuration of the TriggerModeSpec type for use with
// apply.
func TriggerModeSpec() *TriggerModeSpecApplyConfiguration {
	return &TriggerModeSpecApplyConfiguration{}
}

// WithRequeueDuration sets the RequeueDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequeueDuration field is set to the value of the last call.
func (b *TriggerModeSpecApplyConfiguration) WithRequeueDuration(value v1.Duration) *TriggerModeSpecApplyConfiguration {
	b.RequeueDuration = &value
	return b
}

// WithWhen sets the When field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the When field is set to the value of the last call.
func (b *TriggerModeSpecApplyConfiguration) WithWhen(value *WhenWithOutputSpecApplyConfiguration) *TriggerModeSpecApplyConfiguration {
	b.When = value
	return b
}

// WithResponse sets the Response field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Response field is set to the value of the last call.
func (b *TriggerModeSpecApplyConfiguration) WithResponse(value *ResponseOutputSpecApplyConfiguration) *TriggerModeSpecApplyConfiguration {
	b.Response = value
	return b
}
