/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// URLConfigApplyConfiguration represents a declarative configuration of the URLConfig type for use
// with apply.
//
// URLConfig is a template that can be rendered using the Go template engine.
type URLConfigApplyConfiguration struct {
	// Template is a go text template and receives .Environment and .ArgoCDCommitStatus variables. A function called urlQueryEscape
	// is available to escape url query parameters. The template can be configured with options to control the behavior
	// during execution if a variable is not present.
	//
	// Example:
	//
	// {{- $baseURL := "https://dev.argocd.local" -}}
	// {{- if eq .Environment "environment/development" -}}
	// {{- $baseURL = "https://dev.argocd.local" -}}
	// {{- else if eq .Environment "environment/staging" -}}
	// {{- $baseURL = "https://staging.argocd.local" -}}
	// {{- else if eq .Environment "environment/production" -}}
	// {{- $baseURL = "https://prod.argocd.local" -}}
	// {{- end -}}
	// {{- $labels := "" -}}
	// {{- range $key, $value := .ArgoCDCommitStatus.Spec.ApplicationSelector.MatchLabels -}}
	// {{- $labels = printf "%s%s=%s," $labels $key $value -}}
	// {{- end -}}
	// {{ printf "%s/applications?labels=%s" $baseURL (urlQueryEscape $labels) }}
	Template *string `json:"template,omitempty"`
	// Options sets options for the template. Options are described by
	// strings, either a simple string or "key=value". There can be at
	// most one equals sign in an option string. If the option string
	// is unrecognized or otherwise invalid, Option panics.
	//
	// Known options:
	//
	// missingkey: Control the behavior during execution if a map is
	// indexed with a key that is not present in the map.
	//
	// "missingkey=default" or "missingkey=invalid"
	// The default behavior: Do nothing and continue execution.
	// If printed, the result of the index operation is the string
	// "<no value>".
	// "missingkey=zero"
	// The operation returns the zero value for the map type's element.
	// "missingkey=error"
	// Execution stops immediately with an error.
	Options []string `json:"options,omitempty"`
}

// URLConfigApplyConfiguration constructs a declarative configuration of the URLConfig type for use with
// apply.
func URLConfig() *URLConfigApplyConfiguration {
	return &URLConfigApplyConfiguration{}
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *URLConfigApplyConfiguration) WithTemplate(value string) *URLConfigApplyConfiguration {
	b.Template = &value
	return b
}

// WithOptions adds the given value to the Options field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Options field.
func (b *URLConfigApplyConfiguration) WithOptions(values ...string) *URLConfigApplyConfiguration {
	for i := range values {
		b.Options = append(b.Options, values[i])
	}
	return b
}
