/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
)

// WebhookDeliveryApplyConfiguration represents a declarative configuration of the WebhookDelivery type for use
// with apply.
//
// WebhookDelivery configures HTTP webhook delivery.
type WebhookDeliveryApplyConfiguration struct {
	// URL is the HTTP(S) endpoint to deliver the webhook to.
	URL *string `json:"url,omitempty"`
	// Method is the HTTP method used for delivery.
	Method *apiv1alpha1.HTTPMethod `json:"method,omitempty"`
	// Headers is a set of static HTTP headers to send with every request.
	// Values are sent verbatim; do not place secrets here (use signing.secretRef instead).
	Headers map[string]string `json:"headers,omitempty"`
	// Signing, when set, signs the rendered payload using an HMAC secret and adds a
	// signature header so the receiver can verify authenticity.
	Signing *WebhookSigningApplyConfiguration `json:"signing,omitempty"`
	// TimeoutSeconds is the per-attempt request timeout in seconds.
	TimeoutSeconds *int32 `json:"timeoutSeconds,omitempty"`
	// Retry configures retry behavior for failed deliveries.
	Retry *WebhookRetryApplyConfiguration `json:"retry,omitempty"`
}

// WebhookDeliveryApplyConfiguration constructs a declarative configuration of the WebhookDelivery type for use with
// apply.
func WebhookDelivery() *WebhookDeliveryApplyConfiguration {
	return &WebhookDeliveryApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *WebhookDeliveryApplyConfiguration) WithURL(value string) *WebhookDeliveryApplyConfiguration {
	b.URL = &value
	return b
}

// WithMethod sets the Method field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Method field is set to the value of the last call.
func (b *WebhookDeliveryApplyConfiguration) WithMethod(value apiv1alpha1.HTTPMethod) *WebhookDeliveryApplyConfiguration {
	b.Method = &value
	return b
}

// WithHeaders puts the entries into the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Headers field,
// overwriting an existing map entries in Headers field with the same key.
func (b *WebhookDeliveryApplyConfiguration) WithHeaders(entries map[string]string) *WebhookDeliveryApplyConfiguration {
	if b.Headers == nil && len(entries) > 0 {
		b.Headers = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Headers[k] = v
	}
	return b
}

// WithSigning sets the Signing field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Signing field is set to the value of the last call.
func (b *WebhookDeliveryApplyConfiguration) WithSigning(value *WebhookSigningApplyConfiguration) *WebhookDeliveryApplyConfiguration {
	b.Signing = value
	return b
}

// WithTimeoutSeconds sets the TimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutSeconds field is set to the value of the last call.
func (b *WebhookDeliveryApplyConfiguration) WithTimeoutSeconds(value int32) *WebhookDeliveryApplyConfiguration {
	b.TimeoutSeconds = &value
	return b
}

// WithRetry sets the Retry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retry field is set to the value of the last call.
func (b *WebhookDeliveryApplyConfiguration) WithRetry(value *WebhookRetryApplyConfiguration) *WebhookDeliveryApplyConfiguration {
	b.Retry = value
	return b
}
