/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WebRequestCommitStatusEnvironmentStatusApplyConfiguration represents a declarative configuration of the WebRequestCommitStatusEnvironmentStatus type for use
// with apply.
//
// WebRequestCommitStatusEnvironmentStatus defines the observed status for a specific environment.
type WebRequestCommitStatusEnvironmentStatusApplyConfiguration struct {
	// Branch is the name of the branch/environment.
	Branch *string `json:"branch,omitempty"`
	// ReportedSha is the commit SHA being reported on for this environment.
	// This is determined by the reportOn field (proposed or active).
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	ReportedSha *string `json:"reportedSha,omitempty"`
	// LastSuccessfulSha is the last commit SHA that achieved success status for this environment.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	LastSuccessfulSha *string `json:"lastSuccessfulSha,omitempty"`
	// Phase represents the current phase of the validation.
	Phase *string `json:"phase,omitempty"`
	// LastRequestTime is when the last HTTP request was made.
	LastRequestTime *v1.Time `json:"lastRequestTime,omitempty"`
	// LastResponseStatusCode is the HTTP status code from the last request.
	LastResponseStatusCode *int `json:"lastResponseStatusCode,omitempty"`
	// ExpressionData stores custom data returned from the trigger expression.
	// This data is passed to the next trigger expression evaluation.
	ExpressionData map[string]string `json:"expressionData,omitempty"`
}

// WebRequestCommitStatusEnvironmentStatusApplyConfiguration constructs a declarative configuration of the WebRequestCommitStatusEnvironmentStatus type for use with
// apply.
func WebRequestCommitStatusEnvironmentStatus() *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	return &WebRequestCommitStatusEnvironmentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithBranch(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithReportedSha sets the ReportedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportedSha field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithReportedSha(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.ReportedSha = &value
	return b
}

// WithLastSuccessfulSha sets the LastSuccessfulSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulSha field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithLastSuccessfulSha(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.LastSuccessfulSha = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithPhase(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithLastRequestTime sets the LastRequestTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRequestTime field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithLastRequestTime(value v1.Time) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.LastRequestTime = &value
	return b
}

// WithLastResponseStatusCode sets the LastResponseStatusCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastResponseStatusCode field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithLastResponseStatusCode(value int) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.LastResponseStatusCode = &value
	return b
}

// WithExpressionData puts the entries into the ExpressionData field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ExpressionData field,
// overwriting an existing map entries in ExpressionData field with the same key.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithExpressionData(entries map[string]string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	if b.ExpressionData == nil && len(entries) > 0 {
		b.ExpressionData = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ExpressionData[k] = v
	}
	return b
}
