/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WebRequestCommitStatusEnvironmentStatusApplyConfiguration represents a declarative configuration of the WebRequestCommitStatusEnvironmentStatus type for use
// with apply.
//
// WebRequestCommitStatusEnvironmentStatus defines the observed status for a specific environment.
type WebRequestCommitStatusEnvironmentStatusApplyConfiguration struct {
	// Branch is the name of the branch/environment.
	Branch *string `json:"branch,omitempty"`
	// ReportedSha is the commit SHA being reported on for this environment.
	// This is determined by the reportOn field (proposed or active).
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	ReportedSha *string `json:"reportedSha,omitempty"`
	// LastSuccessfulSha is the last commit SHA that achieved success status for this environment.
	// Supports both SHA-1 (40 chars) and SHA-256 (64 chars) Git hash formats.
	LastSuccessfulSha *string `json:"lastSuccessfulSha,omitempty"`
	// Phase represents the current phase of the validation.
	// This controller sets only "pending" or "success"; it never sets "failure" (failure is allowed by the enum for API consistency).
	Phase *apiv1alpha1.CommitStatusPhase `json:"phase,omitempty"`
	// LastRequestTime is when the last HTTP request was made.
	LastRequestTime *v1.Time `json:"lastRequestTime,omitempty"`
	// LastResponseStatusCode is the HTTP status code from the last request.
	LastResponseStatusCode *int `json:"lastResponseStatusCode,omitempty"`
	// TriggerOutput stores the map returned by spec.mode.trigger.when.output.expression.
	// It is passed back into the next reconcile as the TriggerOutput variable (in expressions and templates), making it available
	// to both the trigger when.expression and when.output.expression. Use it to track state across
	// reconcile cycles (e.g. last-seen SHA, attempt counter, last request timestamp).
	// The data is preserved as arbitrary JSON.
	TriggerOutput *apiextensionsv1.JSON `json:"triggerOutput,omitempty"`
	// ResponseOutput stores the map returned by spec.mode.trigger.response.output.expression.
	// This field is ONLY populated when spec.mode.trigger.response is provided.
	// The response output expression is evaluated after each HTTP request and its result is stored here,
	// allowing subsequent trigger expressions to inspect data from the previous response when
	// deciding whether to issue the next request.
	//
	// Without spec.mode.trigger.response, this field will always be nil.
	//
	// Available in trigger expressions and templates as: ResponseOutput.field1, ResponseOutput.field2, etc.
	// (where fields depend on what your response.output.expression returns)
	ResponseOutput *apiextensionsv1.JSON `json:"responseOutput,omitempty"`
}

// WebRequestCommitStatusEnvironmentStatusApplyConfiguration constructs a declarative configuration of the WebRequestCommitStatusEnvironmentStatus type for use with
// apply.
func WebRequestCommitStatusEnvironmentStatus() *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	return &WebRequestCommitStatusEnvironmentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithBranch(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithReportedSha sets the ReportedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportedSha field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithReportedSha(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.ReportedSha = &value
	return b
}

// WithLastSuccessfulSha sets the LastSuccessfulSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulSha field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithLastSuccessfulSha(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.LastSuccessfulSha = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithPhase(value apiv1alpha1.CommitStatusPhase) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithLastRequestTime sets the LastRequestTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRequestTime field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithLastRequestTime(value v1.Time) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.LastRequestTime = &value
	return b
}

// WithLastResponseStatusCode sets the LastResponseStatusCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastResponseStatusCode field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithLastResponseStatusCode(value int) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.LastResponseStatusCode = &value
	return b
}

// WithTriggerOutput sets the TriggerOutput field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TriggerOutput field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithTriggerOutput(value apiextensionsv1.JSON) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.TriggerOutput = &value
	return b
}

// WithResponseOutput sets the ResponseOutput field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResponseOutput field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithResponseOutput(value apiextensionsv1.JSON) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.ResponseOutput = &value
	return b
}
