/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration represents a declarative configuration of the WebRequestCommitStatusPromotionStrategyContextStatus type for use
// with apply.
//
// WebRequestCommitStatusPromotionStrategyContextStatus holds the observed state for context=promotionstrategy (at most one request per WebRequestCommitStatus).
type WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration struct {
	// PhasePerBranch holds the resolved phase for each applicable branch.
	// Every applicable branch is always present after reconciliation.
	PhasePerBranch []WebRequestCommitStatusPhasePerBranchItemApplyConfiguration `json:"phasePerBranch,omitempty"`
	// LastRequestTime is when the last HTTP request was made.
	LastRequestTime *v1.Time `json:"lastRequestTime,omitempty"`
	// LastResponseStatusCode is the HTTP status code from the last request.
	LastResponseStatusCode *int `json:"lastResponseStatusCode,omitempty"`
	// TriggerOutput: same semantics as WebRequestCommitStatusEnvironmentStatus.TriggerOutput, one shared map for context=promotionstrategy.
	TriggerOutput *apiextensionsv1.JSON `json:"triggerOutput,omitempty"`
	// ResponseOutput: same semantics as WebRequestCommitStatusEnvironmentStatus.ResponseOutput, one shared map for context=promotionstrategy.
	ResponseOutput *apiextensionsv1.JSON `json:"responseOutput,omitempty"`
	// LastSuccessfulShas tracks the last SHA that achieved success for each branch.
	// Used with reportOn "proposed" + polling to skip HTTP requests when all environments
	// have already succeeded for their current SHAs.
	LastSuccessfulShas []WebRequestCommitStatusLastSuccessfulShaItemApplyConfiguration `json:"lastSuccessfulShas,omitempty"`
}

// WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration constructs a declarative configuration of the WebRequestCommitStatusPromotionStrategyContextStatus type for use with
// apply.
func WebRequestCommitStatusPromotionStrategyContextStatus() *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration {
	return &WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration{}
}

// WithPhasePerBranch adds the given value to the PhasePerBranch field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PhasePerBranch field.
func (b *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration) WithPhasePerBranch(values ...*WebRequestCommitStatusPhasePerBranchItemApplyConfiguration) *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPhasePerBranch")
		}
		b.PhasePerBranch = append(b.PhasePerBranch, *values[i])
	}
	return b
}

// WithLastRequestTime sets the LastRequestTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRequestTime field is set to the value of the last call.
func (b *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration) WithLastRequestTime(value v1.Time) *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration {
	b.LastRequestTime = &value
	return b
}

// WithLastResponseStatusCode sets the LastResponseStatusCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastResponseStatusCode field is set to the value of the last call.
func (b *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration) WithLastResponseStatusCode(value int) *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration {
	b.LastResponseStatusCode = &value
	return b
}

// WithTriggerOutput sets the TriggerOutput field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TriggerOutput field is set to the value of the last call.
func (b *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration) WithTriggerOutput(value apiextensionsv1.JSON) *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration {
	b.TriggerOutput = &value
	return b
}

// WithResponseOutput sets the ResponseOutput field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResponseOutput field is set to the value of the last call.
func (b *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration) WithResponseOutput(value apiextensionsv1.JSON) *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration {
	b.ResponseOutput = &value
	return b
}

// WithLastSuccessfulShas adds the given value to the LastSuccessfulShas field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LastSuccessfulShas field.
func (b *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration) WithLastSuccessfulShas(values ...*WebRequestCommitStatusLastSuccessfulShaItemApplyConfiguration) *WebRequestCommitStatusPromotionStrategyContextStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithLastSuccessfulShas")
		}
		b.LastSuccessfulShas = append(b.LastSuccessfulShas, *values[i])
	}
	return b
}
