/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// WebRequestCommitStatusSpecApplyConfiguration represents a declarative configuration of the WebRequestCommitStatusSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// WebRequestCommitStatusSpec defines the desired state of WebRequestCommitStatus
type WebRequestCommitStatusSpecApplyConfiguration struct {
	// PromotionStrategyRef references the PromotionStrategy this applies to.
	// The controller will check commits from ALL environments in the referenced PromotionStrategy
	// where this WebRequestCommitStatus.Spec.Key matches an entry in either:
	// - PromotionStrategy.Spec.ProposedCommitStatuses (applies to all environments), OR
	// - PromotionStrategy.Spec.ActiveCommitStatuses (applies to all environments), OR
	// - Environment.ProposedCommitStatuses (applies to specific environment), OR
	// - Environment.ActiveCommitStatuses (applies to specific environment)
	PromotionStrategyRef *ObjectReferenceApplyConfiguration `json:"promotionStrategyRef,omitempty"`
	// Key is the unique identifier for this validation rule.
	// It is used as the commit status key and in status messages.
	// This key is matched against PromotionStrategy's proposedCommitStatuses or activeCommitStatuses
	// to determine which environments this validation applies to.
	Key *string `json:"key,omitempty"`
	// DescriptionTemplate is a human-readable description of this validation that will be shown in the SCM provider
	// (GitHub, GitLab, etc.) as the commit status description.
	// Supports Go templates with environment-specific variables.
	//
	// Available template variables:
	// - {{ .Branch }}: the environment branch name (e.g., "environment/staging")
	// - {{ .ProposedHydratedSha }}: proposed commit SHA for this environment
	// - {{ .ActiveHydratedSha }}: active/deployed commit SHA for this environment
	// - {{ .ReportedSha }}: the commit SHA being reported on
	// - {{ .LastSuccessfulSha }}: last SHA that achieved success for this environment
	// - {{ .Phase }}: current phase (success/pending/failure)
	// - {{ .NamespaceMetadata.Labels }}: map of labels from the namespace
	// - {{ .NamespaceMetadata.Annotations }}: map of annotations from the namespace
	//
	// Examples:
	// - "External approval for {{ .Branch }}"
	// - "Checking deployment {{ .ReportedSha | trunc 7 }}"
	// - "{{ .Phase }} - waiting for external approval"
	//
	// If not specified, defaults to empty string.
	DescriptionTemplate *string `json:"descriptionTemplate,omitempty"`
	// UrlTemplate is a link to more details about this validation that will be shown in the SCM provider
	// (GitHub, GitLab, etc.) as the commit status target URL.
	// Supports Go templates with the same variables as DescriptionTemplate.
	//
	// This can link to:
	// - External approval system UI
	// - Monitoring dashboard
	// - API endpoint being checked
	// - Documentation or runbook
	//
	// Examples:
	// - "https://approvals.example.com/{{ .ReportedSha }}"
	// - "https://dashboard.example.com/{{ .Branch }}/status"
	// - "https://change-api.example.com/changes?asset={{ index .NamespaceMetadata.Labels \"asset-id\" }}"
	//
	// If not specified, defaults to empty string (no URL shown).
	UrlTemplate *string `json:"urlTemplate,omitempty"`
	// ReportOn specifies which commit SHA to report the CommitStatus on.
	// - "proposed": Reports on the proposed hydrated commit SHA (default)
	// - "active": Reports on the active hydrated commit SHA
	//
	// When "proposed": Polls until success, then stops polling for that SHA.
	// When "active": Polls forever, even after success (active state can change).
	ReportOn *string `json:"reportOn,omitempty"`
	// HTTPRequest defines the HTTP request configuration.
	// Supports Go templates in URL, Headers, and Body fields.
	HTTPRequest *HTTPRequestSpecApplyConfiguration `json:"httpRequest,omitempty"`
	// Expression is evaluated using the expr library (github.com/expr-lang/expr) against the HTTP response.
	// The expression must return a boolean value where true indicates the validation passed.
	//
	// Available variables in the expression context:
	// - Response.StatusCode (int): the HTTP response status code
	// - Response.Body (any): parsed JSON as map[string]any, or raw string if not JSON
	// - Response.Headers (map[string][]string): HTTP response headers
	//
	// Examples:
	// - Response.StatusCode == 200
	// - Response.StatusCode == 200 && Response.Body.approved == true
	// - Response.StatusCode == 200 && Response.Body.status == "approved"
	// - len(Response.Headers["X-Approval"]) > 0
	Expression *string `json:"expression,omitempty"`
	// Mode controls how the controller polls or triggers HTTP requests.
	// Exactly one of Polling or Trigger must be specified.
	Mode *ModeSpecApplyConfiguration `json:"mode,omitempty"`
}

// WebRequestCommitStatusSpecApplyConfiguration constructs a declarative configuration of the WebRequestCommitStatusSpec type for use with
// apply.
func WebRequestCommitStatusSpec() *WebRequestCommitStatusSpecApplyConfiguration {
	return &WebRequestCommitStatusSpecApplyConfiguration{}
}

// WithPromotionStrategyRef sets the PromotionStrategyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PromotionStrategyRef field is set to the value of the last call.
func (b *WebRequestCommitStatusSpecApplyConfiguration) WithPromotionStrategyRef(value *ObjectReferenceApplyConfiguration) *WebRequestCommitStatusSpecApplyConfiguration {
	b.PromotionStrategyRef = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *WebRequestCommitStatusSpecApplyConfiguration) WithKey(value string) *WebRequestCommitStatusSpecApplyConfiguration {
	b.Key = &value
	return b
}

// WithDescriptionTemplate sets the DescriptionTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DescriptionTemplate field is set to the value of the last call.
func (b *WebRequestCommitStatusSpecApplyConfiguration) WithDescriptionTemplate(value string) *WebRequestCommitStatusSpecApplyConfiguration {
	b.DescriptionTemplate = &value
	return b
}

// WithUrlTemplate sets the UrlTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UrlTemplate field is set to the value of the last call.
func (b *WebRequestCommitStatusSpecApplyConfiguration) WithUrlTemplate(value string) *WebRequestCommitStatusSpecApplyConfiguration {
	b.UrlTemplate = &value
	return b
}

// WithReportOn sets the ReportOn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportOn field is set to the value of the last call.
func (b *WebRequestCommitStatusSpecApplyConfiguration) WithReportOn(value string) *WebRequestCommitStatusSpecApplyConfiguration {
	b.ReportOn = &value
	return b
}

// WithHTTPRequest sets the HTTPRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HTTPRequest field is set to the value of the last call.
func (b *WebRequestCommitStatusSpecApplyConfiguration) WithHTTPRequest(value *HTTPRequestSpecApplyConfiguration) *WebRequestCommitStatusSpecApplyConfiguration {
	b.HTTPRequest = value
	return b
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *WebRequestCommitStatusSpecApplyConfiguration) WithExpression(value string) *WebRequestCommitStatusSpecApplyConfiguration {
	b.Expression = &value
	return b
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *WebRequestCommitStatusSpecApplyConfiguration) WithMode(value *ModeSpecApplyConfiguration) *WebRequestCommitStatusSpecApplyConfiguration {
	b.Mode = value
	return b
}
