/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WebRequestCommitStatusEnvironmentStatusApplyConfiguration represents a declarative configuration of the WebRequestCommitStatusEnvironmentStatus type for use
// with apply.
//
// WebRequestCommitStatusEnvironmentStatus defines the observed status for a specific environment.
type WebRequestCommitStatusEnvironmentStatusApplyConfiguration struct {
	// Branch is the environment branch name being validated.
	Branch *string `json:"branch,omitempty"`
	// ProposedHydratedSha is the proposed hydrated commit SHA from the PromotionStrategy.
	ProposedHydratedSha *string `json:"proposedHydratedSha,omitempty"`
	// ActiveHydratedSha is the active hydrated commit SHA from the PromotionStrategy.
	ActiveHydratedSha *string `json:"activeHydratedSha,omitempty"`
	// ReportedSha is the SHA where the CommitStatus was reported (based on reportOn field).
	ReportedSha *string `json:"reportedSha,omitempty"`
	// LastSuccessfulSha is the SHA that last achieved success.
	// Used to detect SHA changes - when ReportedSha != LastSuccessfulSha, polling continues.
	// When they match and phase is success, polling stops (for reportOn: proposed).
	LastSuccessfulSha *string `json:"lastSuccessfulSha,omitempty"`
	// Phase represents the current validation state of the commit.
	// - "pending": validation has not completed, HTTP request pending, or expression returned false
	// - "success": expression evaluated to true
	// - "failure": expression compilation failed
	Phase *string `json:"phase,omitempty"`
	// LastRequestTime is when the HTTP request was last made.
	LastRequestTime *v1.Time `json:"lastRequestTime,omitempty"`
	// Response contains information about the HTTP response from the last request.
	Response *ResponseInfoApplyConfiguration `json:"response,omitempty"`
	// ExpressionResult contains the boolean result of the expression evaluation.
	// Only set when the expression successfully evaluates to a boolean.
	ExpressionResult *bool `json:"expressionResult,omitempty"`
	// ExpressionData contains custom data returned by the polling expression.
	// When the polling expression returns an object with fields beyond 'polling',
	// those fields are stored here and made available in the next reconcile.
	// This enables stateful polling logic that can track changes over time.
	ExpressionData *apiextensionsv1.JSON `json:"expressionData,omitempty"`
}

// WebRequestCommitStatusEnvironmentStatusApplyConfiguration constructs a declarative configuration of the WebRequestCommitStatusEnvironmentStatus type for use with
// apply.
func WebRequestCommitStatusEnvironmentStatus() *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	return &WebRequestCommitStatusEnvironmentStatusApplyConfiguration{}
}

// WithBranch sets the Branch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Branch field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithBranch(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.Branch = &value
	return b
}

// WithProposedHydratedSha sets the ProposedHydratedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProposedHydratedSha field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithProposedHydratedSha(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.ProposedHydratedSha = &value
	return b
}

// WithActiveHydratedSha sets the ActiveHydratedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveHydratedSha field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithActiveHydratedSha(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.ActiveHydratedSha = &value
	return b
}

// WithReportedSha sets the ReportedSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportedSha field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithReportedSha(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.ReportedSha = &value
	return b
}

// WithLastSuccessfulSha sets the LastSuccessfulSha field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulSha field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithLastSuccessfulSha(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.LastSuccessfulSha = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithPhase(value string) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithLastRequestTime sets the LastRequestTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastRequestTime field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithLastRequestTime(value v1.Time) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.LastRequestTime = &value
	return b
}

// WithResponse sets the Response field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Response field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithResponse(value *ResponseInfoApplyConfiguration) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.Response = value
	return b
}

// WithExpressionResult sets the ExpressionResult field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpressionResult field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithExpressionResult(value bool) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.ExpressionResult = &value
	return b
}

// WithExpressionData sets the ExpressionData field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpressionData field is set to the value of the last call.
func (b *WebRequestCommitStatusEnvironmentStatusApplyConfiguration) WithExpressionData(value apiextensionsv1.JSON) *WebRequestCommitStatusEnvironmentStatusApplyConfiguration {
	b.ExpressionData = &value
	return b
}
