/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen-v0.20. DO NOT EDIT.

package v1alpha1

// WhenSpecApplyConfiguration represents a declarative configuration of the WhenSpec type for use
// with apply.
//
// WhenSpec holds spec.success.when.expression (evaluated every reconcile, not just after HTTP requests).
// Trigger guards use WhenWithOutputSpec under spec.mode.trigger.when, not this type.
type WhenSpecApplyConfiguration struct {
	// Expression uses github.com/expr-lang/expr and is evaluated every reconcile to determine the commit status phase.
	// When an HTTP request was made this reconcile, Response is populated; otherwise Response is nil.
	//
	// Available variables (same as spec.mode.trigger.when.expression, plus Response):
	// - Response (map or nil): the HTTP response from this reconcile's request, nil when no request was made.
	// When non-nil: Response.StatusCode (int), Response.Body (parsed JSON as map[string]any, or raw string), Response.Headers (map[string][]string).
	// - PromotionStrategy (PromotionStrategy): the full PromotionStrategy spec and status
	// - Environment (EnvironmentStatus): current environment's status from PromotionStrategy (environments context only; nil in promotionstrategy context)
	// - Phase (string): phase from the previous reconcile
	// - ReportedSha (string): the SHA being validated (environments context only; empty in promotionstrategy context)
	// - LastSuccessfulSha (string): last SHA that achieved success (environments context only; empty in promotionstrategy context)
	// - TriggerOutput (map[string]any): custom data from the previous when.output.expression evaluation
	// - ResponseOutput (map[string]any): response data from the previous HTTP request (if any)
	//
	// Important: since the expression runs every reconcile, it must handle Response being nil (no HTTP request
	// this reconcile). Expressions that only reference Response.* will error when Response is nil, causing the
	// reconcile to return an error and requeue. Guard Response access:
	// Response != nil ? Response.StatusCode == 200 : <fallback>
	//
	// Evaluation scope follows spec.mode.context; see ModeSpec. Return shape:
	//
	// - "environments": must return boolean — true → success, false → pending; failure phase is not expressible.
	//
	// - "promotionstrategy": boolean true/false applies the same phase to all applicable environments (success or pending only), or return an object with optional defaultPhase ("success"|"pending"|"failure", default "pending") and optional environments: [{ branch, phase }, ...] for per-branch phases. Example:
	// { defaultPhase: "pending", environments: [{ branch: "dev", phase: "success" }, { branch: "staging", phase: "pending" }] }.
	Expression *string `json:"expression,omitempty"`
}

// WhenSpecApplyConfiguration constructs a declarative configuration of the WhenSpec type for use with
// apply.
func WhenSpec() *WhenSpecApplyConfiguration {
	return &WhenSpecApplyConfiguration{}
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *WhenSpecApplyConfiguration) WithExpression(value string) *WhenSpecApplyConfiguration {
	b.Expression = &value
	return b
}
