apiVersion: promoter.argoproj.io/v1alpha1
kind: RestoreActiveCommit
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: restoreactivecommit-sample
spec:
  promotionStrategyRef:
    name: example-promotion-strategy
  branch: environment/development
  sha: abcdef1234567890abcdef1234567890abcdef12
