apiVersion: promoter.argoproj.io/v1alpha1
kind: DependentsSuccessfulCommitStatus
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: dependentssuccessfulcommitstatus-sample
spec:
  key: dependents-successful
  promotionStrategyRef:
    name: promotionstrategy-sample
