apiVersion: promoter.argoproj.io/v1alpha1
kind: PromotionStrategy
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: promotionstrategy-sample
spec:
  gitRepositoryRef:
    name: promoter-testing
  activeCommitStatuses:
    - key: healthy
    - key: healthy-load
    - key: argocd-health  # ArgoCDCommitStatus.spec.key
    - key: timer          # TimedCommitStatus.spec.key
  proposedCommitStatuses:
    - key: revert-check          # GitCommitStatus (active target)
    - key: commit-format-check   # GitCommitStatus (proposed target)
#    - key: healthy-lint
  environments:
    - branch: environment/development
      autoMerge: true
    - branch: environment/staging
    - branch: environment/production
      activeCommitStatuses:
        - key: healthy
        - key: healthy-load
        - key: argocd-health
        - key: timer