apiVersion: promoter.argoproj.io/v1alpha1
kind: TimedCommitStatus
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: timedcommitstatus-sample
spec:
  # key: timer  # optional; must match PromotionStrategy activeCommitStatuses
  promotionStrategyRef:
    name: promotionstrategy-sample
  environments:
    - branch: environment/development
      duration: 30m
    - branch: environment/staging
      duration: 1h
    - branch: environment/production
      duration: 2h
