apiVersion: promoter.argoproj.io/v1alpha1
kind: ChangeTransferPolicy
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: changetransferpolicy-sample
spec:
  gitRepositoryRef:
    name: promoter-testing
  proposedBranch: environment/development-next
  activeBranch: environment/development
  proposedCommitStatuses:
    - key: deployment-freeze
  activeCommitStatuses:
    - key: healthy
