apiVersion: promoter.argoproj.io/v1alpha1
kind: TimedCommitStatus
metadata:
  labels:
    app.kubernetes.io/name: promoter
    app.kubernetes.io/managed-by: kustomize
  name: timedcommitstatus-sample
spec:
  # key: timer  # optional; must match PromotionStrategy active/proposedCommitStatuses
  promotionStrategyRef:
    name: ps-name
  environments: []
