apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook-ps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: helm-guestbook-ps
  source:
    repoURL: https://github.com/emirot/gitops-promoter-examples
    path: helm-guestbook-promotion
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true