/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package dashboard

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	promoterv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
)

// PromotionStrategyDetails is the internal representation of the dashboard
// aggregation bundle. See the v1alpha1 package for field documentation. As an
// internal ("hub") type it carries no JSON tags; conversion to/from the versioned
// type is generated by conversion-gen.
//
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type PromotionStrategyDetails struct {
	metav1.TypeMeta
	metav1.ObjectMeta

	PromotionStrategy        promoterv1alpha1.PromotionStrategy
	ChangeTransferPolicies   []promoterv1alpha1.ChangeTransferPolicy
	PullRequests             []promoterv1alpha1.PullRequest
	CommitStatuses           []promoterv1alpha1.CommitStatus
	ArgoCDCommitStatuses     []promoterv1alpha1.ArgoCDCommitStatus
	GitCommitStatuses        []promoterv1alpha1.GitCommitStatus
	TimedCommitStatuses      []promoterv1alpha1.TimedCommitStatus
	WebRequestCommitStatuses []promoterv1alpha1.WebRequestCommitStatus
	GitRepository            *promoterv1alpha1.GitRepository
	ScmProvider              *promoterv1alpha1.ScmProvider
	ClusterScmProvider       *promoterv1alpha1.ClusterScmProvider
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// PromotionStrategyDetailsList contains a list of PromotionStrategyDetails.
type PromotionStrategyDetailsList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []PromotionStrategyDetails
}
