//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	dashboard "github.com/argoproj-labs/gitops-promoter/api/dashboard/dashboard"
	apiv1alpha1 "github.com/argoproj-labs/gitops-promoter/api/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*PromotionStrategyDetails)(nil), (*dashboard.PromotionStrategyDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PromotionStrategyDetails_To_dashboard_PromotionStrategyDetails(a.(*PromotionStrategyDetails), b.(*dashboard.PromotionStrategyDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*dashboard.PromotionStrategyDetails)(nil), (*PromotionStrategyDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_dashboard_PromotionStrategyDetails_To_v1alpha1_PromotionStrategyDetails(a.(*dashboard.PromotionStrategyDetails), b.(*PromotionStrategyDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PromotionStrategyDetailsList)(nil), (*dashboard.PromotionStrategyDetailsList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PromotionStrategyDetailsList_To_dashboard_PromotionStrategyDetailsList(a.(*PromotionStrategyDetailsList), b.(*dashboard.PromotionStrategyDetailsList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*dashboard.PromotionStrategyDetailsList)(nil), (*PromotionStrategyDetailsList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_dashboard_PromotionStrategyDetailsList_To_v1alpha1_PromotionStrategyDetailsList(a.(*dashboard.PromotionStrategyDetailsList), b.(*PromotionStrategyDetailsList), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_PromotionStrategyDetails_To_dashboard_PromotionStrategyDetails(in *PromotionStrategyDetails, out *dashboard.PromotionStrategyDetails, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.PromotionStrategy = in.PromotionStrategy
	out.ChangeTransferPolicies = *(*[]apiv1alpha1.ChangeTransferPolicy)(unsafe.Pointer(&in.ChangeTransferPolicies))
	out.PullRequests = *(*[]apiv1alpha1.PullRequest)(unsafe.Pointer(&in.PullRequests))
	out.CommitStatuses = *(*[]apiv1alpha1.CommitStatus)(unsafe.Pointer(&in.CommitStatuses))
	out.ArgoCDCommitStatuses = *(*[]apiv1alpha1.ArgoCDCommitStatus)(unsafe.Pointer(&in.ArgoCDCommitStatuses))
	out.GitCommitStatuses = *(*[]apiv1alpha1.GitCommitStatus)(unsafe.Pointer(&in.GitCommitStatuses))
	out.TimedCommitStatuses = *(*[]apiv1alpha1.TimedCommitStatus)(unsafe.Pointer(&in.TimedCommitStatuses))
	out.WebRequestCommitStatuses = *(*[]apiv1alpha1.WebRequestCommitStatus)(unsafe.Pointer(&in.WebRequestCommitStatuses))
	out.GitRepository = (*apiv1alpha1.GitRepository)(unsafe.Pointer(in.GitRepository))
	out.ScmProvider = (*apiv1alpha1.ScmProvider)(unsafe.Pointer(in.ScmProvider))
	out.ClusterScmProvider = (*apiv1alpha1.ClusterScmProvider)(unsafe.Pointer(in.ClusterScmProvider))
	return nil
}

// Convert_v1alpha1_PromotionStrategyDetails_To_dashboard_PromotionStrategyDetails is an autogenerated conversion function.
func Convert_v1alpha1_PromotionStrategyDetails_To_dashboard_PromotionStrategyDetails(in *PromotionStrategyDetails, out *dashboard.PromotionStrategyDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_PromotionStrategyDetails_To_dashboard_PromotionStrategyDetails(in, out, s)
}

func autoConvert_dashboard_PromotionStrategyDetails_To_v1alpha1_PromotionStrategyDetails(in *dashboard.PromotionStrategyDetails, out *PromotionStrategyDetails, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.PromotionStrategy = in.PromotionStrategy
	out.ChangeTransferPolicies = *(*[]apiv1alpha1.ChangeTransferPolicy)(unsafe.Pointer(&in.ChangeTransferPolicies))
	out.PullRequests = *(*[]apiv1alpha1.PullRequest)(unsafe.Pointer(&in.PullRequests))
	out.CommitStatuses = *(*[]apiv1alpha1.CommitStatus)(unsafe.Pointer(&in.CommitStatuses))
	out.ArgoCDCommitStatuses = *(*[]apiv1alpha1.ArgoCDCommitStatus)(unsafe.Pointer(&in.ArgoCDCommitStatuses))
	out.GitCommitStatuses = *(*[]apiv1alpha1.GitCommitStatus)(unsafe.Pointer(&in.GitCommitStatuses))
	out.TimedCommitStatuses = *(*[]apiv1alpha1.TimedCommitStatus)(unsafe.Pointer(&in.TimedCommitStatuses))
	out.WebRequestCommitStatuses = *(*[]apiv1alpha1.WebRequestCommitStatus)(unsafe.Pointer(&in.WebRequestCommitStatuses))
	out.GitRepository = (*apiv1alpha1.GitRepository)(unsafe.Pointer(in.GitRepository))
	out.ScmProvider = (*apiv1alpha1.ScmProvider)(unsafe.Pointer(in.ScmProvider))
	out.ClusterScmProvider = (*apiv1alpha1.ClusterScmProvider)(unsafe.Pointer(in.ClusterScmProvider))
	return nil
}

// Convert_dashboard_PromotionStrategyDetails_To_v1alpha1_PromotionStrategyDetails is an autogenerated conversion function.
func Convert_dashboard_PromotionStrategyDetails_To_v1alpha1_PromotionStrategyDetails(in *dashboard.PromotionStrategyDetails, out *PromotionStrategyDetails, s conversion.Scope) error {
	return autoConvert_dashboard_PromotionStrategyDetails_To_v1alpha1_PromotionStrategyDetails(in, out, s)
}

func autoConvert_v1alpha1_PromotionStrategyDetailsList_To_dashboard_PromotionStrategyDetailsList(in *PromotionStrategyDetailsList, out *dashboard.PromotionStrategyDetailsList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]dashboard.PromotionStrategyDetails)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PromotionStrategyDetailsList_To_dashboard_PromotionStrategyDetailsList is an autogenerated conversion function.
func Convert_v1alpha1_PromotionStrategyDetailsList_To_dashboard_PromotionStrategyDetailsList(in *PromotionStrategyDetailsList, out *dashboard.PromotionStrategyDetailsList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PromotionStrategyDetailsList_To_dashboard_PromotionStrategyDetailsList(in, out, s)
}

func autoConvert_dashboard_PromotionStrategyDetailsList_To_v1alpha1_PromotionStrategyDetailsList(in *dashboard.PromotionStrategyDetailsList, out *PromotionStrategyDetailsList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]PromotionStrategyDetails)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_dashboard_PromotionStrategyDetailsList_To_v1alpha1_PromotionStrategyDetailsList is an autogenerated conversion function.
func Convert_dashboard_PromotionStrategyDetailsList_To_v1alpha1_PromotionStrategyDetailsList(in *dashboard.PromotionStrategyDetailsList, out *PromotionStrategyDetailsList, s conversion.Scope) error {
	return autoConvert_dashboard_PromotionStrategyDetailsList_To_v1alpha1_PromotionStrategyDetailsList(in, out, s)
}
