name: Kubebuilder Helm Chart Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

# this version will need to match the one in https://github.com/argoproj-labs/gitops-promoter-helm/
env:
  KUBEBUILDER_VERSION: v4.12.0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  helm-chart-validation:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # pin@v4
      - name: Set up Go
        uses: actions/setup-go@4aaadf42668403795cdfdb15b1c4250e9fed12b9 # pin@v5
        with:
          go-version: "1.25"

      - name: Install kubebuilder
        run: |
          curl -L -o kubebuilder "https://github.com/kubernetes-sigs/kubebuilder/releases/download/${{ env.KUBEBUILDER_VERSION }}/kubebuilder_$(go env GOOS)_$(go env GOARCH)"
          chmod +x kubebuilder && sudo mv kubebuilder /usr/local/bin/
          kubebuilder version

      - name: Set up Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # pin v4.3
        with:
          version: v3.20.0

      - name: Generate Helm chart with Kubebuilder
        run: |
          kubebuilder edit --plugins=helm/v2-alpha --output-dir=./tmp_chart --manifests=./dist/install.yaml

      - name: Update example blocks from generated CRDs
        run: |
          sed -i 's/{{- if eq \(.Environment\)/{{ `{{- if eq .Environment` }}/g; s/{{- else if eq \(.Environment\)/{{ `{{- else if eq .Environment` }}/g; s/{{- end -}}/{{ `{{- end -}}` }}/g; s/{{- range \$key, \$value := \.ArgoCDCommitStatus/{{ `{{- range $key, $value := .ArgoCDCommitStatus` }}/g' tmp_chart/chart/templates/crd/argocdcommitstatuses.promoter.argoproj.io.yaml

      - name: Lint Helm chart
        run: |
          # we set these to true to match the defaults from the Helm chart's values.yaml
          helm lint --debug ./tmp_chart/chart  --set crd.enable=true --set webhook.enable=true

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: helm-chart
          path: ./tmp_chart
          retention-days: 3
